import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {onArchiveRequest} from '../functions/_lib/fiction-archives.js';
import {createFictionHandler} from '../functions/_lib/fiction-service.js';
import * as engine from '../functions/_lib/fiction-lab-engine.js';
function database(){const sql=new DatabaseSync(':memory:');return {sql,prepare(q){let a=[];return {bind(...v){a=v;return this;},async run(){return {meta:{changes:Number(sql.prepare(q).run(...a).changes)}};},async first(){return sql.prepare(q).get(...a)||null;}};},async batch(stmts){sql.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
function client(db=database()){
 const cookies=new Map(),env={DB:db};let game;
 const handler=createFictionHandler(engine,{gameKind:'lab',cookieName:'koa_fiction_lab',cookiePath:'/api/fiction-lab',fetchImpl:()=>{throw Error('archive must not use model');}});
 const req=async(body,extra={})=>{const response=await (extra.game?handler:onArchiveRequest)({env,request:new Request('https://game.test/api/fiction-lab'+(extra.game?'':'/archives')+(extra.id?'?id='+extra.id:''),{method:body?'POST':'GET',headers:{Cookie:extra.cookies??[...cookies].map(([k,v])=>k+'='+v).join('; '),'Content-Type':'application/json',Origin:extra.origin||'https://game.test','CF-Connecting-IP':'192.0.2.201'},...(body?{body:JSON.stringify(body)}:{})})});const set=response.headers.get('Set-Cookie');if(set){const [name,value]=set.split(';')[0].split('=');cookies.set(name,value);}const data=await response.json();return {status:response.status,body:data,headers:response.headers};};
 return {db,cookies,req,async start(){const r=await req({op:'start',reset:true},{game:true});game=r.body.game;return game;},save(title='白垩未燃的那一夜',extra={}){return req({op:'save',title,sessionId:game.sessionId,expectedRevision:game.revision,...extra});},setState(change){const row=db.sql.prepare('select * from koa_fiction_sessions where session_id=?').get(game.sessionId);const state=JSON.parse(row.state_json);change(state);db.sql.prepare('update koa_fiction_sessions set state_json=?,revision=? where session_id=?').run(JSON.stringify(state),state.revision,state.sessionId);game=engine.getView(state);return game;}};
}
test('named snapshot uses saved server view; survives a new adventure and current-session expiry',async()=>{const c=client();assert.equal((await c.req()).status,200);assert.match((await c.req()).headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax; Max-Age=31536000/);await c.start();c.setState(s=>{s.log.push({role:'player',turn:1,text:'<img src=x onerror=alert(1)>白垩未燃'});s.revision=1;s.turn=1;s.status='ended';s.ending={id:'leave',title:'带着观察归来',text:'故事结束。'};});const saved=await c.save();assert.equal(saved.status,200);const a=saved.body.archive;assert.equal(a.title,'白垩未燃的那一夜');assert.equal(a.game.status,'ended');assert.equal(a.game.log.at(-1).text,'<img src=x onerror=alert(1)>白垩未燃');assert.ok(!('entities' in a.game));assert.ok(!('state_json' in a));const owner=c.cookies.get('koa_fiction_collection');await c.start();assert.equal(c.cookies.get('koa_fiction_collection'),owner);assert.equal((await c.req()).body.entries[0].id,a.id);c.db.sql.prepare('update koa_fiction_sessions set expires_at=0').run();assert.equal((await c.req(null,{id:a.id})).body.archive.title,a.title);});
test('snapshot retry does not duplicate; later snapshots preserve earlier story and renaming changes only title',async()=>{const c=client();await c.req();await c.start();const first=(await c.save('最初的门')).body.archive;const retry=(await c.save('最初的门')).body.archive;assert.equal(first.id,retry.id);assert.equal((await c.req()).body.entries.length,1);c.setState(s=>{s.revision++;s.turn++;s.log.push({role:'player',turn:s.turn,text:'后来我点燃了厚布'});});const later=(await c.save('布角的火光')).body.archive;assert.notEqual(later.id,first.id);assert.equal((await c.req(null,{id:first.id})).body.archive.game.log.length,first.game.log.length);const renamed=(await c.req({op:'rename',id:first.id,title:'门外的一夜'})).body.archive;assert.equal(renamed.title,'门外的一夜');assert.deepEqual(renamed.game,first.game);});
test('collection requires its own cookie; another browser cannot read, rename or delete archives',async()=>{const a=client();await a.start();assert.equal((await a.save()).status,401);await a.req();const saved=(await a.save()).body.archive;const b=client(a.db);await b.req();for(const body of [null,{op:'rename',id:saved.id,title:'冒名修改'},{op:'delete',id:saved.id}])assert.equal((await b.req(body,body?{}:{id:saved.id})).status,404);assert.equal((await a.req(null,{id:saved.id,cookies:''})).status,401);assert.equal((await a.req({op:'delete',id:saved.id},{origin:'https://other.test'})).status,403);assert.equal((await a.req(null,{id:saved.id})).status,200);});
test('save rejects stale revision, running turns and supplied state; active snapshot does not end game',async()=>{const c=client();await c.req();await c.start();assert.equal((await c.save('伪造',{game:{log:[]}})).status,400);assert.equal((await c.save('过期',{expectedRevision:20})).status,409);c.db.sql.prepare('update koa_fiction_sessions set lock_until=?').run(Date.now()+30000);assert.equal((await c.save()).body.code,'turn_busy');c.db.sql.prepare('update koa_fiction_sessions set lock_until=0').run();const saved=await c.save();assert.equal(saved.status,200);assert.equal(saved.body.archive.game.status,'playing');assert.equal(JSON.parse(c.db.sql.prepare('select state_json from koa_fiction_sessions').get().state_json).revision,0);});
test('archive title validation, deletion and collection capacity are bounded',async()=>{const c=client();await c.req();await c.start();for(const title of ['', ' ', 'a'.repeat(61),'换\n行'])assert.equal((await c.save(title)).status,400);const first=(await c.save()).body.archive;const row=c.db.sql.prepare('select * from koa_fiction_archives').get();for(let i=1;i<100;i++)c.db.sql.prepare('insert into koa_fiction_archives(id,owner_hash,session_id,revision,title,snapshot_json,created_at,updated_at) values(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),row.owner_hash,row.session_id,i,'收藏'+i,row.snapshot_json,Date.now(),Date.now());assert.equal((await c.save('容量满仍可改同一快照标题')).status,200);c.setState(s=>{s.revision=100;s.turn=100;});assert.equal((await c.save()).body.code,'collection_full');assert.equal((await c.req({op:'delete',id:first.id})).status,200);assert.equal((await c.req(null,{id:first.id})).status,404);assert.equal((await c.save()).status,200);assert.equal((await c.req()).body.entries.length,100);});
test('archive mutation rechecks revision at insertion, including concurrent gameplay after initial read',async()=>{const c=client();await c.req();await c.start();const original=c.db.prepare;let intercepted=false;c.db.prepare=q=>{if(q.startsWith('INSERT INTO koa_fiction_archives')&&!intercepted){intercepted=true;c.db.sql.prepare('update koa_fiction_sessions set revision=revision+1').run();}return original(q);};assert.equal((await c.save()).status,409);assert.equal((await c.req()).body.entries.length,0);});
