import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import * as engine from '../functions/_lib/fiction-lab-engine.js';
import * as classic from '../functions/_lib/fiction-engine.js';
import {createFictionHandler,callModel} from '../functions/_lib/fiction-service.js';
import {resolveLabTurn} from '../functions/_lib/fiction-lab-host.js';
const step=(over={})=>({attempt:'尝试',status:'completed',beat:'action',requires_previous_success:false,scope:'near',refs:[],move_to:'stay',door:'unchanged',end:'continue',updates:[],creates:[],outcome:'发生了一次尝试。',observations:[],...over});
const update=(id,facts,place='carried',integrity='intact')=>({id,facts,place,integrity});
const decision={disposition:'none',needed:false,question:'',pending_action:'',reason:''};
const plan=(...steps)=>({intent:'执行玩家尝试',steps,memory_updates:[],decision:{...decision},evolution:{basis:'none',updates:[],observations:[]}});
const apply=(s,...steps)=>engine.applyProposal(s,plan(...steps),'测试动作');
const evo=(steps,basis,updates=[])=>({...plan(...steps),evolution:{basis,updates,observations:[]}});
const paused=()=>({...plan(step({status:'failed',outcome:'白垩受热但没有燃烧，尚未投出。'})),decision:{disposition:'replace',needed:true,question:'白垩没有燃起来，仍然投出吗？',pending_action:'将白垩投到门内近处',reason:'试火目的可能落空，投出将失去手中白垩。'}});
const clothChange={id:'cloth',facts:'布已烧尽，只剩冷灰。',integrity:'consumed',reason:'明确长时间等待，先前燃烧的布料耗尽。'};
test('there is no fuel/turn limit; turn is only a passage number',()=>{let s=engine.createGame();for(let i=0;i<65;i++)s=apply(s,step({beat:'confirmation',scope:'observe'})).state;assert.equal(s.turn,65);assert.equal(s.status,'playing');assert.equal(engine.getView(s).remainingTurns,undefined);assert.equal(engine.hostContext(s).remaining,undefined);assert.equal(engine.hostContext(s).time,undefined);assert.equal(engine.MAX_TURNS,null);});
test('legacy active and fuel-ended saves migrate without resetting items or revision; voluntary endings remain ended',()=>{for(const ended of [false,true]){const s=engine.createGame();s.version=2;s.turn=20;s.revision=7;s.entities.find(e=>e.id==='cloth').facts='湿角仍在。';if(ended){s.status='ended';s.ending={id:'time'};}const migrated=engine.normalizeGame(s);assert.equal(migrated.version,3);assert.equal(migrated.turn,7);assert.equal(migrated.status,'playing');assert.equal(migrated.entities.find(e=>e.id==='cloth').facts,'湿角仍在。');assert.equal(s.version,2);}const s=engine.createGame();s.version=2;s.status='ended';s.ending={id:'leave'};assert.equal(engine.normalizeGame(s).status,'ended');});
test('coherent preparation and remote throw preserve actor location and persistent damage',()=>{const s=engine.createGame();const r=apply(s,step({updates:[update('lamp','灯罩打开，正常燃烧。')]}),step({scope:'project',updates:[update('cloth','布角燃烧。','threshold','damaged')]}));assert.equal(s.revision,0);assert.equal(r.state.location,'outside');assert.equal(r.state.entities.find(e=>e.id==='cloth').place,'threshold');assert.ok(!engine.getView(r.state).inventory.some(e=>e.id==='cloth'));assert.equal(r.state.turn,1);});
test('explicit dependency stops after failure; independent follow-up can execute',()=>{const next=step({scope:'project',updates:[update('chalk','落在门内。','threshold')]});const s=engine.createGame();const stop=apply(s,step({status:'failed'}),{...next,requires_previous_success:true});assert.equal(stop.outcomes.length,1);const go=apply(s,step({status:'failed'}),next);assert.equal(go.state.entities.find(e=>e.id==='chalk').place,'threshold');});
test('decision preserves item and pending purpose; confirmation freezes ongoing processes',()=>{let s=engine.applyProposal(engine.createGame(),paused(),'点燃白垩再投掷').state;assert.ok(s.pendingDecision);assert.equal(s.entities.find(e=>e.id==='chalk').place,'carried');const p={...paused(),evolution:{basis:'action',updates:[clothChange],observations:[]}};assert.throws(()=>engine.applyProposal(s,p,'再问一次'),/evolution cause/);const saved=structuredClone(s.pendingDecision);s=engine.applyProposal(s,{...plan(step({beat:'confirmation',scope:'observe'})),decision:{...saved,disposition:'keep'}},'为什么要确认').state;assert.deepEqual(s.pendingDecision,saved);assert.equal(s.entities.find(e=>e.id==='chalk').place,'carried');});
test('partial completion stops the chain and rejects passive penalties',()=>{const s=engine.createGame();assert.equal(apply(s,step({status:'partial'}),step({move_to:'threshold',scope:'travel'})).state.location,'outside');assert.throws(()=>engine.applyProposal(s,evo([step({status:'partial'})],'action',[clothChange]),'暂停'),/evolution cause/);assert.throws(()=>apply(s,step({beat:'confirmation',updates:[update('cloth','变湿')]})),/confirmation effects/);});
test('closed boundaries, direct remote pickup, fixed objects, resurrection and copying are bounded',()=>{const s=engine.createGame();s.doorOpen=false;assert.throws(()=>apply(s,step({scope:'project',updates:[update('cloth','投出','threshold')]})),/reach/);assert.throws(()=>apply(s,step({move_to:'chamber',scope:'travel'})),/travel/);assert.throws(()=>apply(s,step({updates:[update('wall','拿走')]})),/fixed/);assert.throws(()=>apply(s,step({creates:[{id:'copy',source:'cloth',name:'厚布副本',place:'carried',facts:'完整'}]})),/source/);const dead=apply(s,step({updates:[update('cloth','已消耗','consumed','consumed')]})).state;assert.throws(()=>apply(dead,step({updates:[update('cloth','复原')]})),/resurrection/);});
test('derived pieces retain origin and require source loss',()=>{const r=apply(engine.createGame(),step({updates:[update('cloth','撕去一角','carried','damaged')],creates:[{id:'cloth_strip',source:'cloth',name:'厚布布条',place:'carried',facts:'撕下的一角'}]}));assert.equal(r.state.entities.find(e=>e.id==='cloth_strip').source,'cloth');assert.equal(r.state.entities.find(e=>e.id==='cloth').integrity,'damaged');});
test('hammer fires once, interrupts movement, and mixing release and travel is rejected',()=>{const s=engine.createGame();assert.throws(()=>apply(s,step({scope:'project',move_to:'threshold',updates:[update('weight','移开','outside')]})),/split support/);s.location='threshold';const hit=apply(s,step({scope:'project',updates:[update('weight','移开','threshold')]}),step({move_to:'outside',scope:'travel'}));assert.equal(hit.state.location,'threshold');assert.equal(hit.state.resolve,2);assert.equal(hit.outcomes.length,1);const safe=apply(s,step({move_to:'outside',scope:'travel'}),step({updates:[update('weight','移开','outside')]}));assert.equal(safe.state.resolve,3);assert.equal(safe.state.hammerFallen,true);assert.equal(safe.state.pendingDecision,null);assert.equal(apply(safe.state,step()).state.resolve,3);});
test('explicit waiting can evolve off-screen fire; public notes preserve last seen until door opens',()=>{let s=apply(engine.createGame(),step({scope:'project',updates:[update('cloth','布角正在燃烧。','threshold','damaged')]}),step({door:'closed'})).state;const r=engine.applyProposal(s,evo([step({beat:'wait',scope:'wait'})],'wait',[clothChange]),'等待明火熄灭');assert.equal(r.state.entities.find(e=>e.id==='cloth').integrity,'consumed');const known=engine.getView(r.state).clues.find(e=>e.id==='cloth');assert.match(known.title,/上次所见/);assert.match(known.text,/正在燃烧/);const open=apply(r.state,step({door:'open'})).state;assert.match(engine.getView(open).clues.find(e=>e.id==='cloth').text,/烧尽/);});
test('evolution requires actual matching cause and cannot repair/create/consume protected entities',()=>{const s=engine.createGame();assert.throws(()=>engine.applyProposal(s,evo([step({beat:'confirmation'})],'wait',[clothChange]),'问问'),/cause/);assert.throws(()=>engine.applyProposal(s,evo([step()],'none',[clothChange]),'无变化'),/paused evolution/);assert.throws(()=>engine.applyProposal(s,evo([step()],'action',[{...clothChange,id:'new_item'}]),'造物'),/evolution id/);assert.throws(()=>engine.applyProposal(s,evo([step()],'action',[{...clothChange,id:'weight'}]),'消耗石镇'),/protected/);s.entities.find(e=>e.id==='cloth').integrity='damaged';assert.throws(()=>engine.applyProposal(s,evo([step()],'action',[{...clothChange,integrity:'intact'}]),'修复'),/repair/);});
function database(){const sql=new DatabaseSync(':memory:');return {sql,prepare(q){let a=[];return {bind(...v){a=v;return this;},async run(){return {meta:{changes:Number(sql.prepare(q).run(...a).changes)}};},async first(){return sql.prepare(q).get(...a)||null;}};},async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const approved=(consistent=true)=>({consistent,issue:consistent?'':'意图被替换',issue_code:consistent?'none':'intent',narration:consistent?'白垩仍在手中。':''});
function fixture(sequence){let calls=0,cookie='';const inputs=[],diagnostics=[],env={DB:database(),UPSTREAM_API_KEY:'test',UPSTREAM_BASE_URL:'https://model.invalid/v1'};const handler=createFictionHandler(engine,{gameKind:'lab',cookieName:'koa_fiction_lab',cookiePath:'/api/fiction-lab',resolveTurn:args=>resolveLabTurn({...args,diagnostic:e=>{diagnostics.push(e);args.diagnostic?.(e);}}),fetchImpl:async(_,opts)=>{const payload=JSON.parse(opts.body);inputs.push(payload);const value=sequence?sequence(calls++,payload):(calls++,payload.text.format.name==='host_ruling'?plan(step()):approved());return new Response(JSON.stringify({status:'completed',output_text:JSON.stringify(value),usage:{input_tokens:100,output_tokens:100}}));}});const old=createFictionHandler(classic);return {env,inputs,diagnostics,old,get calls(){return calls;},async req(body,{target=handler,rawCookie=cookie,query=''}={}){const r=await target({env,request:new Request('https://game.test/api/fiction-lab'+query,{method:body?'POST':'GET',headers:{Cookie:rawCookie,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.55'},...(body?{body:JSON.stringify(body)}:{})})});if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json(),cookie};}};}
const turn=(revision=0,action='观察')=>({op:'turn',expectedRevision:revision,requestId:crypto.randomUUID(),action});
test('start uses no model; reviewed turn and receipt commit once',async()=>{const f=fixture();await f.req({op:'start'});assert.equal(f.calls,0);const b=turn(),r=await f.req(b);assert.equal(r.status,200);assert.equal(f.calls,2);assert.equal(r.body.game.turn,1);assert.deepEqual((await f.req(b)).body,r.body);assert.equal(f.calls,2);});
test('API accepts migrated fuel-ended saves and plays beyond old limit without restoring consumed items',async()=>{const f=fixture();await f.req({op:'start'});const row=f.env.DB.sql.prepare('select * from koa_fiction_sessions').get();const s=JSON.parse(row.state_json);s.version=2;s.turn=40;s.revision=41;s.status='ended';s.ending={id:'time'};Object.assign(s.entities.find(e=>e.id==='cloth'),{place:'consumed',integrity:'consumed',facts:'烧尽'});f.env.DB.sql.prepare('update koa_fiction_sessions set state_json=?,revision=?').run(JSON.stringify(s),41);assert.equal((await f.req()).body.game.status,'playing');const r=await f.req(turn(41));assert.equal(r.status,200);assert.equal(r.body.game.turn,42);assert.ok(!r.body.game.inventory.some(e=>e.id==='cloth'));});
test('one rejected review retries original state once and receipt skips further calls',async()=>{const f=fixture((n,p)=>p.text.format.name==='host_ruling'?plan(step({updates:[update('cloth','湿角')]})):approved(n!==1));await f.req({op:'start'});const b=turn(),r=await f.req(b);assert.equal(r.status,200);assert.equal(f.calls,4);assert.equal(r.body.game.revision,1);assert.equal(JSON.parse(f.inputs[2].input[1].content).world.entities.find(e=>e.id==='cloth').facts,'干燥、完好。');assert.equal(f.diagnostics.length,1);assert.deepEqual((await f.req(b)).body,r.body);assert.equal(f.calls,4);});
test('two failed reviews leave original state and receipts untouched, release lock',async()=>{const f=fixture((_,p)=>p.text.format.name==='host_ruling'?plan(step()):approved(false));await f.req({op:'start'});assert.equal((await f.req(turn())).body.code,'adjudication_failed');assert.equal(f.calls,4);assert.equal((await f.req()).body.game.revision,0);assert.equal(f.env.DB.sql.prepare('select count(*) n from koa_fiction_receipts').get().n,0);assert.equal(f.env.DB.sql.prepare('select lock_owner from koa_fiction_sessions').get().lock_owner,null);});
test('pending decision survives GET, is included in next host context and clears on committed continuation',async()=>{const f=fixture((n,p)=>p.text.format.name==='host_ruling'?(n===0?paused():{...plan(step({scope:'project',updates:[update('chalk','投出','threshold')]})),decision:{...decision,disposition:'resolve'}}):approved());await f.req({op:'start'});await f.req(turn(0,'点燃白垩然后扔进去'));assert.ok((await f.req()).body.game.pendingDecision);const r=await f.req(turn(1,'照样扔'));assert.equal(r.status,200);assert.equal(r.body.game.pendingDecision,null);assert.match(JSON.parse(f.inputs[2].input[1].content).world.pendingDecision.pending_action,/白垩/);});
test('classic and trial sessions remain isolated, budget is still enforced without an in-world clock',async()=>{const f=fixture();const lab=await f.req({op:'start'});assert.equal((await f.req(null,{target:f.old,rawCookie:lab.cookie.replace('koa_fiction_lab=','koa_fiction=')})).body.game,null);f.env.FICTION_DAILY_BUDGET_USD='0';assert.equal((await f.req(turn())).body.code,'budget_exhausted');assert.equal(f.calls,0);assert.equal((await f.req()).body.game.revision,0);});
test('late review is rejected; malformed review can be corrected once',async()=>{const realNow=Date.now;let now=1000,calls=0;Date.now=()=>now;try{await assert.rejects(resolveLabTurn({state:engine.createGame(),body:{action:'观察'},diagnostic:()=>{},call:async()=>{if(++calls===1)return JSON.stringify(plan(step()));now=91001;return JSON.stringify(approved());}}),e=>e.code==='model_unavailable');}finally{Date.now=realNow;}calls=0;const r=await resolveLabTurn({state:engine.createGame(),body:{action:'观察'},diagnostic:()=>{},call:async()=>{calls++;return calls%2?JSON.stringify(plan(step())):calls===2?'null':JSON.stringify(approved());}});assert.equal(calls,4);assert.equal(r.state.revision,1);});

test('decision contract preserves original purpose until explicit resolution or cancellation',()=>{const s=engine.applyProposal(engine.createGame(),paused(),'点燃白垩再投掷').state;assert.throws(()=>apply(s,step({beat:'confirmation'})),/unresolved decision/);const p=plan(step({beat:'confirmation'}));delete p.decision;assert.throws(()=>engine.applyProposal(s,p,'追问'),/decision/);assert.throws(()=>engine.applyProposal(s,{...plan(step({beat:'confirmation'})),decision:{...decision,disposition:'resolve'}},'为什么'),/resolution/);const kept=engine.applyProposal(s,{...plan(step({beat:'confirmation'})),decision:{...s.pendingDecision,disposition:'keep',question:'解释后的问题'}},'再说一下').state;assert.equal(kept.pendingDecision.originalAction,'点燃白垩再投掷');assert.equal(engine.applyProposal(kept,{...plan(step({beat:'confirmation'})),decision:{...decision,disposition:'cancel'}},'算了不扔').state.pendingDecision,null);});
test('forced hammer interruption retains unexecuted plan and freezes passive evolution',()=>{const s=engine.createGame();Object.assign(s.entities.find(e=>e.id==='cloth'),{facts:'布角燃烧',integrity:'damaged'});const steps=[step({updates:[update('weight','移开','outside')]}),step({attempt:'随后走进门内',scope:'travel',move_to:'threshold'})];const result=engine.applyProposal(s,plan(...steps),'移开石镇再进门');assert.equal(result.outcomes.length,1);assert.match(result.state.pendingDecision.pending_action,/走进门内/);assert.throws(()=>engine.applyProposal(s,evo(steps,'action',[clothChange]),'移开石镇再进门'),/evolution cause/);});

test('hammer preserves follow-up carried only in decision rather than executable steps',()=>{const p=paused();p.steps=[step({status:'partial',updates:[update('weight','移开','outside')]})];p.decision.pending_action='随后进门并观察地面';const r=engine.applyProposal(engine.createGame(),p,'移石镇再进门');assert.equal(r.state.pendingDecision.pending_action,'随后进门并观察地面');});

test('trace records actual payload and response, survives restore, stays outside model memory and receipts',async()=>{const f=fixture();f.env.UPSTREAM_API_KEY='secret-never-in-trace';await f.req({op:'start'});assert.deepEqual((await f.req(null,{query:'?trace=list'})).body.entries,[]);const action=turn();await f.req(action);const list=(await f.req(null,{query:'?trace=list'})).body.entries;assert.equal(list.length,1);const trace=(await f.req(null,{query:'?trace='+list[0].id})).body.trace;assert.equal(trace.status,'committed');assert.equal(trace.calls.length,2);assert.deepEqual(trace.calls[0].request,f.inputs[0]);assert.equal(JSON.parse(trace.calls[0].response.output_text).intent,'执行玩家尝试');assert.doesNotMatch(JSON.stringify(trace),/secret-never-in-trace|Authorization|upstream.invalid/);assert.equal(trace.calls[1].response.usage.input_tokens,100);await f.req(action);assert.equal(f.calls,2);assert.equal((await f.req(null,{query:'?trace=list'})).body.entries.length,1);await f.req(turn(1));assert.ok(!('trace' in JSON.parse(f.inputs[2].input[1].content).world));assert.ok(!('calls' in JSON.parse(f.env.DB.sql.prepare('select state_json from koa_fiction_sessions').get().state_json)));});
test('trace shows rejected and corrected calls; failed turns remain inspectable without committing',async()=>{const f=fixture((n,p)=>p.text.format.name==='host_ruling'?plan(step()):approved(n!==1));await f.req({op:'start'});await f.req(turn());let row=f.env.DB.sql.prepare('select trace_json from koa_fiction_traces').get();let trace=JSON.parse(row.trace_json);assert.equal(trace.calls.length,4);assert.equal(trace.checks.length,1);assert.match(trace.checks[0].code,/intent/);assert.ok(JSON.parse(trace.calls[2].request.input[1].content).correction);const fail=fixture((n,p)=>p.text.format.name==='host_ruling'?plan(step()):approved(false));await fail.req({op:'start'});assert.equal((await fail.req(turn())).status,503);trace=JSON.parse(fail.env.DB.sql.prepare('select trace_json from koa_fiction_traces').get().trace_json);assert.equal(trace.status,'failed');assert.equal(trace.calls.length,4);assert.equal(trace.errorCode,'adjudication_failed');assert.equal((await fail.req()).body.game.revision,0);});
test('trace access is session-scoped, expires, paginates, and uses a separate read quota',async()=>{const f=fixture();const first=await f.req({op:'start'});await f.req(turn());const id=(await f.req(null,{query:'?trace=list'})).body.entries[0].id;const before=f.env.DB.sql.prepare("select count from koa_fiction_limits where bucket like 'api:%'").get().count;await f.req(null,{query:'?trace=list'});assert.equal(f.env.DB.sql.prepare("select count from koa_fiction_limits where bucket like 'api:%'").get().count,before);await f.req({op:'start',reset:true});assert.equal((await f.req(null,{query:'?trace='+id})).status,404);assert.equal((await f.req(null,{query:'?trace='+id,rawCookie:''})).status,401);assert.equal((await f.req(null,{query:'?trace='+id,rawCookie:first.cookie,target:f.old})).status,401);assert.equal((await f.req(null,{query:'?trace=list&before=nan'})).status,400);const original=f.env.DB.sql.prepare('select * from koa_fiction_traces').get();for(let i=0;i<24;i++)f.env.DB.sql.prepare('insert into koa_fiction_traces(session_id,revision,action,status,trace_json,created_at,expires_at) values(?,?,?,?,?,?,?)').run(original.session_id,i,'测试','committed',original.trace_json,Date.now(),Date.now()+10000);const a=(await f.req(null,{query:'?trace=list',rawCookie:first.cookie})).body;assert.equal(a.entries.length,20);const b=(await f.req(null,{query:'?trace=list&before='+a.nextBefore,rawCookie:first.cookie})).body;assert.equal(b.entries.length,5);assert.equal(b.nextBefore,null);f.env.DB.sql.prepare('update koa_fiction_traces set expires_at=0').run();assert.equal((await f.req(null,{query:'?trace='+id,rawCookie:first.cookie})).status,404);});
test('trace excludes raw provider errors and storage failure does not undo successful gameplay',async()=>{const f=fixture();await f.req({op:'start'});f.env.FICTION_DAILY_BUDGET_USD='0';assert.equal((await f.req(turn())).status,429);let trace=JSON.parse(f.env.DB.sql.prepare('select trace_json from koa_fiction_traces').get().trace_json);assert.equal(trace.calls[0].status,'not_sent');assert.equal(trace.calls[0].request,undefined);assert.equal(trace.errorCode,'budget_exhausted');const ok=fixture();await ok.req({op:'start'});const prepare=ok.env.DB.prepare;ok.env.DB.prepare=q=>{if(q.startsWith('INSERT INTO koa_fiction_traces'))throw Error('test-only storage outage');return prepare(q);};assert.equal((await ok.req(turn())).status,200);assert.equal((await ok.req()).body.game.revision,1);});

test('upstream error bodies and authorization never enter trace records',async()=>{const traceCall={},db=database();const f=fixture();await f.req({op:'start'});await assert.rejects(callModel({...f.env,UPSTREAM_API_KEY:'secret-authorization-sentinel'},f.env.DB,async()=>new Response('private-provider-error-sentinel',{status:500}),[{role:'user',content:'测试'}],{traceCall}),e=>e.code==='model_unavailable');assert.equal(traceCall.status,'failed');assert.equal(traceCall.response,undefined);assert.doesNotMatch(JSON.stringify(traceCall),/secret-authorization-sentinel|private-provider-error-sentinel|Authorization/);});
