import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {sqliteAdapter} from '../scripts/fiction-preview.mjs';
import {createMultiplayerHandler} from '../functions/_lib/multiplayer/service.js';
import {createAdventure} from '../functions/_lib/multiplayer/host.js';
import {applyRuling,schemasFor} from '../functions/_lib/multiplayer/v3/host.js';
import {buildContext} from '../functions/_lib/multiplayer/v3/context.js';
import {regroup,visibleLog,transferItem} from '../functions/_lib/multiplayer/v3/scenes.js';
import {prepareHistory,hydrateHistory,historyPage,historySchema} from '../functions/_lib/multiplayer/history-store.js';
import {storyFor} from '../functions/_lib/multiplayer/stories/registry.js';
const members=Array.from({length:5},(_,i)=>({id:'P'+i,name:'队员'+i}));
const make=(n=2)=>createAdventure(members.slice(0,n),'cooperative-v3');
const actions=s=>s.scenes[s.sceneId].participants.map(playerId=>({playerId,text:'我留在此处观察',hold:false}));
const proposal=(s,a=actions(s))=>({destination:s.location,route:[s.location],progress:{...s.progress},ended:false,suspicionDelta:0,suspicionReason:'',coordination:a.map(x=>({playerId:x.playerId,basis:'stay',agreementId:''})),outcomes:a.map(x=>({playerId:x.playerId,kind:'observation',text:'看清了码头正在卸货。'})),items:[],removeItems:[],memoryUpdates:[],sceneSummary:{place:s.location,text:'大家在码头观察。'}});
function fixture(){const sql=new DatabaseSync(':memory:'),db=sqliteAdapter(sql),env={DB:db,FICTION_MULTIPLAYER_HOST_REVISION:'cooperative-v3'},handler=createMultiplayerHandler({resolver:async({state,actions:a})=>{const n=applyRuling(state,proposal(state,a),a);n.log.push(...a.map(x=>({id:crypto.randomUUID(),round:n.round,role:'player',playerId:x.playerId,name:x.name,text:x.text,audience:state.characters.map(c=>c.id)})),{id:crypto.randomUUID(),round:n.round,role:'host',name:'主持',text:'回应本次行动。',audience:state.characters.map(c=>c.id)});n.drafts={};return {state:n};}});
const client=()=>{let cookie='';return {async req(body,query=''){const r=await handler({env,request:new Request('https://x.test/api/fiction-rooms'+query,{method:body?'POST':'GET',headers:{Cookie:cookie,...(body?{'Content-Type':'application/json',Origin:'https://x.test'}:{})},...(body?{body:JSON.stringify(body)}:{})})});if(r.headers.has('Set-Cookie'))cookie=r.headers.get('Set-Cookie').split(';')[0];return {status:r.status,cookie:r.headers.get('Set-Cookie'),...await r.json()};}};};return {sql,env,client};}
const op=(op,data={})=>({op,table:20000,...data});
async function start(f,n=2){const cs=[];for(let i=0;i<n;i++){const c=f.client();await c.req({op:'hello',name:'队员'+i});await c.req(op('join'));cs.push(c);}assert.equal((await cs[0].req(op('start',{requestId:crypto.randomUUID()}))).status,200);return cs;}
test('v3 pins scenario adapter and validates progress without changing v2',()=>{const s=make();assert.equal(storyFor(s).revision,'prisoner-13-v3');assert.deepEqual(schemasFor(s).proposal.properties.progress.required,['keyCopied']);assert.equal(createAdventure(members.slice(0,2),'cooperative-v2').version,2);const p=proposal(s);p.progress.keyCopied=true;assert.throws(()=>applyRuling(s,p,actions(s)),/目标/);});
test('blocked actions retain last meaningful response and accumulate attention',()=>{let s=make(),p=proposal(s);p.outcomes[0].kind='blocked';s=applyRuling(s,p,actions(s));s=applyRuling(s,p,actions(s));assert.equal(s.attention.P0.blockedStreak,2);assert.equal(s.memory.spotlight.P0,undefined);assert.equal(s.memory.spotlight.P1,2);const c=buildContext(s,actions(s),[],storyFor(s));assert.equal(c.sceneBrief.attention[0].blockedStreak,2);assert.equal(c.sceneBrief.derived,true);});
test('memory distinguishes a claim from settled fact; scene brief is rebuilt',()=>{const s=make(),p=proposal(s);p.memoryUpdates=[{id:'promise',kind:'commitment',basis:'claim',text:'离场归还借物',status:'active',owner:'P0',places:['dock'],knownBy:['P0'],evidence:[{round:1,kind:'action',playerId:'P0'}]}];const n=applyRuling(s,p,actions(s));assert.equal(n.memory.entries[0].basis,'claim');p.memoryUpdates[0].basis='event';assert.throws(()=>applyRuling(s,p,actions(s)),/结算依据/);});
test('five-person two-scene probe preserves positions, audiences and unique transfer',()=>{const s=make(5),story=storyFor(s),cs=members.map((m,i)=>({playerId:m.id,destination:i<2?'lift':'dock',route:i<2?['dock','lift']:['dock']}));const split=regroup(s,[{id:'up',location:'lift',participants:['P0','P1']},{id:'down',location:'dock',participants:['P2','P3','P4']}],cs,story);assert.equal(split.positions.P4,'dock');assert.throws(()=>transferItem(split,'P0_tools','P2','P0'));assert.equal(visibleLog([{text:'A',audience:['P0','P1']}],'P2').length,0);split.sceneId='up';split.location='lift';const n=applyRuling(split,proposal(split),actions(split));assert.equal(n.positions.P4,'dock');assert.equal(n.journal[0].outcomes.length,2);assert.throws(()=>applyRuling(split,proposal(split),[...actions(split),{playerId:'P4',text:'观察'}]));const joined=regroup(n,[{id:'main',location:'dock',participants:members.map(m=>m.id)}],members.map(m=>({playerId:m.id,destination:'dock',route:n.positions[m.id]==='lift'?['lift','dock']:['dock']})),story);const moved=transferItem(joined,'P0_tools','P2','P0');assert.equal(moved.items.filter(i=>i.id==='P0_tools').length,1);assert.equal(moved.items.find(i=>i.id==='P0_tools').owner,'P2');});
test('pause frees table, lists only participant saves and restores same identity/version',async()=>{const f=fixture(),[a,b]=await start(f),before=(await a.req(null,'?table=20000')).table.game;assert.equal((await b.req(op('pause',{title:'冰海书签'}))).status,403);assert.equal((await a.req(op('pause',{title:'冰海书签'}))).status,200);assert.equal((await a.req()).saves[0].title,'冰海书签');const x=f.client();await x.req({op:'hello',name:'外人'});assert.equal((await x.req()).saves.length,0);assert.equal((await x.req(op('restore',{runId:before.runId}))).status,404);assert.equal((await b.req(op('restore',{runId:before.runId}))).status,200);assert.equal((await b.req(op('resume'))).code,'waiting_for_party');assert.equal((await a.req(op('join'))).status,200);assert.equal((await b.req(op('resume'))).status,200);const g=(await a.req(null,'?table=20000')).table.game;assert.equal(g.runId,before.runId);assert.equal(g.hostRevision,before.hostRevision);assert.equal(g.round,0);assert.equal((await b.req()).saves.length,0);f.sql.close();});
test('leaving pauses without auto-actions, original member returns and last leave saves',async()=>{const f=fixture(),[a,b]=await start(f);await b.req(op('leave'));assert.equal((await a.req(op('act',{round:0,text:'走',hold:false}))).code,'game_paused');assert.equal((await b.req(op('join'))).status,200);assert.equal((await a.req(op('resume'))).status,200);await a.req(op('leave'));await b.req(op('leave'));assert.equal((await b.req()).saves.length,1);assert.equal((await b.req()).tables[0].status,'waiting');f.sql.close();});
test('simultaneous restore cannot clone one run onto two tables',async()=>{const f=fixture(),[a,b]=await start(f);const id=(await a.req(null,'?table=20000')).table.game.runId;await a.req(op('pause',{title:'同一局'}));const rs=await Promise.all([a.req(op('restore',{runId:id})),b.req(op('restore',{table:20001,runId:id}))]);assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(f.sql.prepare("SELECT count(*) n FROM koa_fiction_multi_tables WHERE json_extract(state_json,'$.runId')=?").get(id).n,1);f.sql.close();});
test('v3 immutable history survives hot-state trimming, paging, pause and restore',async()=>{const f=fixture(),cs=await start(f);for(let i=0;i<45;i++){f.sql.prepare('DELETE FROM koa_fiction_limits').run();for(const c of cs)await c.req(op('act',{round:i,text:'观察变化',hold:false}));assert.equal((await cs[0].req(op('resolve',{round:i,requestId:crypto.randomUUID()}))).status,200);}const raw=JSON.parse(f.sql.prepare('SELECT state_json FROM koa_fiction_multi_tables WHERE table_no=20000').get().state_json);assert.equal(raw.log.length,12);assert.equal(raw.journal.length,6);const g=(await cs[0].req(null,'?table=20000&window=1')).table.game;assert.equal(g.log.length,40);assert.equal(g.history.hasOlder,true);let old=g;while(old.history.hasOlder)old=(await cs[0].req(null,'?table=20000&window=1&before='+old.history.first)).table.game;assert.equal(old.log[0].round,0);await cs[0].req(op('pause',{title:'长局'}));await cs[0].req(op('restore',{runId:g.runId}));await cs[1].req(op('join'));await cs[0].req(op('resume'));assert.equal((await cs[0].req(null,'?table=20000')).table.game.log.length,136);f.sql.close();});

test('incremental history writes only new records and resolves old evidence after trimming',async()=>{
 const sql=new DatabaseSync(':memory:'),db=sqliteAdapter(sql);await db.batch([db.prepare(historySchema)]);
 let s=make();const a=actions(s);a[0].text='我答应离开时归还借来的工具';
 for(let i=0;i<20;i++){const p=proposal(s,a);s=applyRuling(s,p,a);s.log.push(...a.map(x=>({id:crypto.randomUUID(),round:s.round,role:'player',playerId:x.playerId,text:x.text,audience:['P0','P1']})),{id:crypto.randomUUID(),round:s.round,role:'host',text:'看清了码头正在卸货。',audience:['P0','P1']});const pack=prepareHistory(db,s);assert.equal(pack.statements.length,i===0?5:4);await db.batch(pack.statements);s=await hydrateHistory(db,pack.state);assert.equal(prepareHistory(db,s).statements.length,0);}
 const p=proposal(s,a);p.memoryUpdates=[{id:'old',kind:'commitment',basis:'claim',text:'离开时归还工具',status:'active',owner:'P0',places:['dock'],knownBy:['P0','P1'],evidence:[{round:1,kind:'action',playerId:'P0'}]}];assert.equal(applyRuling(s,p,a).memory.entries[0].source.round,1);sql.close();
});
test('actual history pagination filters private audiences before limiting',async()=>{
 const sql=new DatabaseSync(':memory:'),db=sqliteAdapter(sql);await db.batch([db.prepare(historySchema)]);const s=make();s.log=Array.from({length:100},(_,i)=>({id:String(i),round:i,text:i%2?'secret':'public',audience:i%2?['P1']:['P0']}));const pack=prepareHistory(db,s);await db.batch(pack.statements);const page=await historyPage(db,pack.state,'P0',new URL('https://x/?window=1'));assert.equal(page.log.length,40);assert.equal(page.history.total,50);assert.ok(page.log.every(e=>e.text==='public'));assert.equal(page.log[0].seq,20);sql.close();
});
test('scene authority and context do not mix distant actors, events or evidence',()=>{
 let s=make(5),story=storyFor(s);s=regroup(s,[{id:'up',location:'lift',participants:['P0','P1']},{id:'down',location:'dock',participants:['P2','P3','P4']}],members.map((m,i)=>({playerId:m.id,destination:i<2?'lift':'dock',route:i<2?['dock','lift']:['dock']})),story);
 s.log.push({id:'private',round:1,role:'player',playerId:'P2',text:'远处的秘密',audience:['P2']});s.memory.entries.push({id:'private-memory',kind:'clue',text:'远处的秘密',basis:'event',status:'active',places:['dock'],knownBy:['P2'],evidence:[]});
 const c=buildContext(s,actions(s),[{playerId:'P2',text:'私密讨论'}],story);assert.equal(c.world.characters.length,2);assert.ok(!JSON.stringify(c).includes('远处的秘密'));assert.equal(c.chat.messages.length,0);
 const bad=structuredClone(s);bad.location='dock';assert.throws(()=>applyRuling(bad,proposal(bad),actions(bad)),/不一致/);
 const end=proposal(s);end.destination='escape';end.route=['lift','dock','escape'];end.coordination.forEach(c=>c.basis='current');end.ended=true;assert.throws(()=>applyRuling(s,end,actions(s)),/未离场/);
});

test('active identities renew browser cookie, not just database expiry',async()=>{const f=fixture(),[a]=await start(f);assert.match((await a.req()).cookie,/Max-Age=2592000/);f.sql.close();});
test('pause and seat changes roll back when their atomic commit fails',async()=>{
 const f=fixture(),[a,b]=await start(f),before=f.sql.prepare('SELECT state_json FROM koa_fiction_multi_tables WHERE table_no=20000').get().state_json;
 const prepare=f.env.DB.prepare.bind(f.env.DB);let inject=true;f.env.DB.prepare=q=>{const st=prepare(q),run=st.run.bind(st);st.run=async()=>{if(inject&&q.startsWith('UPDATE koa_fiction_multi_tables SET state_json=')){inject=false;throw Error('injected failure');}return run();};return st;};
 assert.equal((await a.req(op('pause',{title:'失败不丢档'}))).status,503);assert.equal(f.sql.prepare('SELECT count(*) n FROM koa_fiction_multi_saves').get().n,0);assert.equal(f.sql.prepare('SELECT count(*) n FROM koa_fiction_multi_players WHERE table_no=20000').get().n,2);assert.equal(f.sql.prepare('SELECT state_json FROM koa_fiction_multi_tables WHERE table_no=20000').get().state_json,before);
 const x=f.client();await x.req({op:'hello',name:'另一桌'});inject=true;assert.equal((await x.req(op('join',{table:20001}))).status,503);assert.equal((await x.req()).you.table,null);f.sql.close();
});
