import {eligible,applyAuthoredEffects,followCompanions} from './authored-events.js';
import {initializeMemory,recordObservations,applyMemories,retrieveHistory} from '../fiction-lab-memory.js';
const assert=(yes,why,details)=>{if(!yes){const error=Error('LAB_INVALID:'+why);if(details)error.details=details;throw error;}};
const text=(v,n=700)=>typeof v==='string'&&v.trim().length>0&&v.length<=n;
export function createAdventureEngine(story){
 const places=story.places,ids=Object.keys(places),adjacent=(a,b)=>a===b||places[a]?.exits.includes(b);
 const physical=(e,s)=>e.place==='carried'?s.location:e.place==='consumed'?e.lastPlace:e.place;
 const gateOpen=(s,a,b)=>!story.gates.some(g=>((g.a===a&&g.b===b)||(g.a===b&&g.b===a))&&!s.flags.includes(g.flag));
 const allowedTravel=(s,a,b)=>adjacent(a,b)&&gateOpen(s,a,b)&&!(story.id==='ghosts-of-aramoor'&&s.flags.includes('sailed')&&['deck','hold'].includes(b)&&!['deck','hold'].includes(a));
 const visibleExit=(s,id)=>!story.gates.some(g=>g.hidden&&((g.a===s.location&&g.b===id)||(g.b===s.location&&g.a===id))&&!s.flags.includes(g.flag));
 const normalizeGame=s=>s.memoryVersion===1?s:initializeMemory(structuredClone(s));
 const credits={scenario:story.title,original:story.original,author:story.author,source:story.source,license:story.license,licenseText:story.licenseText||null,adaptation:story.publication==='author-permitted'?'百页行 · 经作者许可的单人改编':'Koa-OL 非官方中文单人改编'};
 function createGame(){const s={version:1,storyId:story.id,gameKind:'adventure:'+story.id,placeIds:ids,sessionId:'',revision:0,turn:0,location:story.start,visited:[story.start],status:'playing',ending:null,resolve:3,flags:[],memoryOffers:[],notes:[],events:[],pendingDecision:null,entities:structuredClone(story.entities),knownEntities:{},log:[{role:'narrator',turn:0,text:story.opening}]};for(const e of s.entities)if(e.place==='carried'||e.place===s.location)s.knownEntities[e.id]=structuredClone(e);return initializeMemory(s);}
 function getActions(s){if(s.status!=='playing')return [];return [{id:'look',label:'仔细观察这里，寻找可用的线索'},...places[s.location].exits.filter(id=>visibleExit(s,id)&&!(story.id==='ghosts-of-aramoor'&&s.flags.includes('sailed')&&['deck','hold'].includes(id)&&!['deck','hold'].includes(s.location))).map(id=>({id:'go_'+id,label:gateOpen(s,s.location,id)?'谨慎前往'+places[id].name:'查看通往'+places[id].name+'的门，寻找打开的办法'})),...(s.location===story.start&&story.allowLeaveAtStart!==false?[{id:'leave',label:'结束这次冒险，从这里离开'}]:[]),...(story.suggestions||[]).filter(x=>eligible(x,s)&&(!x.places||x.places.includes(s.location))).map(({id,label})=>({id,label}))];}
 function getView(saved){const s=normalizeGame(saved);return {title:story.title,credits,sessionId:s.sessionId,revision:s.revision,turn:s.turn,pendingDecision:s.pendingDecision,location:{id:s.location,name:places[s.location].name,description:s.status==='ended'?'这次冒险已经结束；这里是最后经过的地点。':(story.id==='ghosts-of-aramoor'&&s.flags.includes('sailed')&&s.location==='camp'?'旧海盗船已经离港。洞内沙滩留下营地与通向斜道、海水的路。':places[s.location].description)},status:s.status,ending:s.ending,inventory:s.entities.filter(e=>e.place==='carried').map(e=>({id:e.id,name:e.name,description:e.facts})),clues:[...Object.values(s.knownEntities).filter(e=>e.place!=='carried').map(e=>({id:e.id,title:(e.kind==='npc'?'人物记录':e.name)+' · 上次所见',text:e.facts})),...s.observationHistory.slice(-16).map(n=>({id:n.id,title:'历史观察 · 第 '+n.revision+' 段',text:n.text}))],map:ids.filter(id=>s.visited.includes(id)||(places[s.location].exits.includes(id)&&visibleExit(s,id))).map(id=>({id,name:places[id].name,visited:s.visited.includes(id),current:s.location===id})),choices:getActions(s),log:s.log,stats:{resolve:s.resolve,treasure:s.observationHistory.length},model:'gpt-5.6-sol'};}
 function hostContext(saved,action=''){const s=normalizeGame(saved);return {rulesVersion:7,title:story.title,mode:'causal_no_clock',status:s.status,ending:s.ending,location:s.location,visited:s.visited,resolve:s.resolve,pendingDecision:s.pendingDecision,places,gates:story.gates,entities:s.entities,knownEntities:Object.values(s.knownEntities).map(({id,place,integrity,facts})=>({id,place,integrity,facts})),flags:s.flags,memoryOffers:s.memoryOffers||[],milestones:story.milestones,endings:story.endings,laws:story.laws,companions:story.companions||[],notes:s.observationHistory.slice(-16),...retrieveHistory(s,action),recent:s.log.slice(-6),recentEvents:s.events.slice(-3)};}
 function applyProposal(original,p,action){original=normalizeGame(original);assert(original.storyId===story.id&&original.status==='playing','session');assert(text(p.intent,500)&&Array.isArray(p.steps)&&p.steps.length>0&&p.steps.length<=6,'steps');const s=structuredClone(original),outcomes=[];
  const d=p.decision;assert(d&&typeof d.needed==='boolean'&&['none','keep','replace','resolve','cancel'].includes(d.disposition),'decision');assert(d.needed===['keep','replace'].includes(d.disposition),'decision disposition');if(['keep','resolve','cancel'].includes(d.disposition))assert(s.pendingDecision,'missing pending decision');if(d.disposition==='none')assert(!s.pendingDecision,'unresolved decision');if(d.needed)assert(text(d.question,300)&&text(d.pending_action,500)&&text(d.reason,400),'decision detail');
  for(const step of p.steps){
   assert(typeof step.requires_previous_success==='boolean','dependency');if(step.requires_previous_success&&outcomes.at(-1)?.status==='failed')break;
   assert(text(step.attempt,400)&&text(step.outcome,700),'text');assert(['completed','partial','failed','clarify'].includes(step.status)&&['action','wait','confirmation'].includes(step.beat),'status');assert(['near','project','observe','travel','wait','communicate'].includes(step.scope),'scope');
   for(const [name,max] of [['refs',16],['updates',16],['creates',3],['observations',4],['achievements',4]])assert(Array.isArray(step[name])&&step[name].length<=max,name);
   assert(step.observations.every(v=>text(v,300)),'observations');assert(step.move_to==='stay'||ids.includes(step.move_to),'travel');assert(step.end==='continue'||story.endings[step.end],'ending');
   const start=s.location,reachable=pos=>pos===start||(['project','observe'].includes(step.scope)&&allowedTravel(s,start,pos));
   for(const id of step.refs)assert(s.entities.some(e=>e.id===id),'unknown ref');
   if(step.status==='clarify'||step.beat==='confirmation')assert(step.beat==='confirmation'&&step.updates.length===0&&step.creates.length===0&&step.achievements.length===0&&step.move_to==='stay'&&step.end==='continue','confirmation effects');
   // Position is evaluated before mutation; moving and operating in the next room
   // are separate ordered steps, not a loophole for remote manipulation.
   if(step.move_to!=='stay')assert(step.beat==='action'&&allowedTravel(s,start,step.move_to),'travel');
   const changed=new Set(),scriptedChanges=[];
   for(const u of step.updates){const e=s.entities.find(v=>v.id===u.id);assert(e&&!changed.has(e.id),'update id');changed.add(e.id);assert(text(u.facts,700)&&['intact','damaged','consumed'].includes(u.integrity)&&['carried','consumed',...ids].includes(u.place),'facts');assert(e.integrity!=='consumed','resurrection');const ritual=e.id==='memory_archive'&&text(step.memory_offer,300);const radio=step.scope==='communicate'&&e.kind==='npc'&&s.entities.some(x=>x.id==='terminal'&&x.place==='carried')&&s.flags.includes('hounds_arrived');assert(reachable(physical(e,s))||ritual||radio,'source reach',{entity:e.id,source:physical(e,s),actor:start,scope:step.scope,hint:'移动与到达后操作必须拆成相邻的先后步骤'});if(radio||ritual)assert(u.place===e.place&&u.integrity===e.integrity,'remote effects');assert((u.integrity==='consumed')===(u.place==='consumed'),'consumption');if(!e.movable)assert(u.place===e.place&&u.integrity!=='consumed','fixed entity');if(e.kind==='npc')assert(u.place!=='carried'&&u.place!=='consumed','npc placement');if(story.id==='ghosts-of-aramoor'&&e.id==='captain')assert(u.place==='deck','captain boundary');if(story.id==='ghosts-of-aramoor'&&e.id==='loot')assert(u.place!=='carried','heavy cargo');
    if(u.place!=='consumed')assert(reachable(u.place==='carried'?start:u.place)||ritual||radio,'destination reach');if(['observe','wait'].includes(step.scope))assert(u.place===e.place,'observe transfer');if(u.place==='carried'&&e.place!=='carried')assert(physical(e,s)===start||step.scope==='project','pickup reach');if(u.integrity==='consumed')e.lastPlace=physical(e,s);Object.assign(e,u,{updatedAtRevision:s.revision+1});s.knownEntities[e.id]=structuredClone(e);
   }
   for(const c of step.creates){const source=s.entities.find(e=>e.id===c.source);assert(source&&source.kind!=='npc'&&changed.has(source.id)&&source.integrity!=='intact','derive source');assert(/^[a-z][a-z0-9_]{1,39}$/.test(c.id)&&!s.entities.some(e=>e.id===c.id)&&s.entities.length<70,'derived id');assert(text(c.name,50)&&text(c.facts,500)&&c.name.includes(source.name),'derived facts');assert(['carried',...ids].includes(c.place)&&reachable(c.place==='carried'?start:c.place),'derived place');const child={id:c.id,name:c.name,nature:'从'+source.name+'实际取出或分离，材质与内容须有来源依据。',place:c.place,facts:c.facts,movable:true,kind:'object',integrity:'intact',source:source.id};s.entities.push(child);s.knownEntities[c.id]=structuredClone(child);}
   // Memory donation requires a verbatim, explicit offer by the player; the host
   // cannot invent an autobiographical sacrifice to unlock a door.
   if(step.memory_offer){s.memoryOffers||=[];assert(!s.memoryOffers.includes(step.memory_offer),'memory already offered');assert(story.id==='library-delve'&&action.includes(step.memory_offer)&&/记忆|回忆/.test(step.memory_offer)&&/献|交|给|换|付|愿|舍/.test(step.memory_offer),'memory consent');assert(changed.has('memory_archive')&&step.achievements.filter(x=>x.startsWith('open_')).length===1,'memory exchange');s.memoryOffers.push(step.memory_offer);}
   if(changed.has('memory_archive'))assert(text(step.memory_offer,300),'memory consent');
   for(const id of step.achievements){const m=story.milestones[id];assert(m&&!s.flags.includes(id),'milestone id');assert((m.beats||['action']).includes(step.beat)&&step.status!=='failed'&&m.places.includes(start),'milestone place');assert(eligible(m,s),'milestone prerequisite');assert(!m.refsAny||m.refsAny.some(ref=>step.refs.includes(ref)),'milestone reference');assert((m.entityRules||[]).every(r=>{const e=s.entities.find(x=>x.id===r.id);return e&&(!r.place||e.place===r.place)&&(!r.notPlace||e.place!==r.notPlace)&&(!r.notPlaces||!r.notPlaces.includes(e.place))&&(!r.intact||e.integrity==='intact');}),'milestone evidence');if(story.id==='library-delve'&&id.startsWith('open_'))assert(step.memory_offer||(step.refs.includes('picks')&&s.entities.find(e=>e.id==='picks')?.place==='carried'),'unlock evidence');if(story.id==='ghosts-of-aramoor'&&['unburdened','sailed'].includes(id)){const cargo=s.entities.filter(e=>e.id==='loot'||e.source==='loot');assert(cargo.every(e=>!['hold','deck','carried'].includes(e.place)),'cargo remains aboard');}s.flags.push(id);scriptedChanges.push(...applyAuthoredEffects(story,s,m));}
   const companionMoves=step.move_to!=='stay'?followCompanions(story,s,start,step.move_to):[];
   if(step.move_to!=='stay'){s.location=step.move_to;if(!s.visited.includes(s.location))s.visited.push(s.location);}
   const outcome={attempt:step.attempt,status:step.status,outcome:step.outcome,observations:step.observations,beat:step.beat,refs:step.refs,changes:step.updates,creates:step.creates,move_to:step.move_to,end:step.end,scope:step.scope,memory_offer:step.memory_offer,achievements:step.achievements,scriptedChanges,companionMoves};outcomes.push(outcome);recordObservations(s,step.observations,s.revision+1,'step');
   if(step.end!=='continue'){const ending=story.endings[step.end];assert((ending.entityRules||[]).every(r=>s.entities.some(e=>e.id===r.id&&(!r.place||e.place===r.place)&&(!r.intact||e.integrity==='intact'))),'ending evidence');assert(step.beat==='action'&&step.status==='completed'&&ending.places.includes(s.location)&&eligible(ending,s),'ending prerequisites');s.status='ended';s.ending={id:step.end,title:ending.title,text:ending.text};break;}
   if(['partial','clarify'].includes(step.status))break;
  }
  if(d.disposition==='replace')assert(['partial','failed','clarify'].includes(outcomes.at(-1)?.status),'decision stopping point');if(d.disposition==='resolve')assert(outcomes.some(e=>e.beat!=='confirmation'),'decision resolution');
  const ev=p.evolution;assert(ev&&['none','action','wait'].includes(ev.basis)&&Array.isArray(ev.updates)&&ev.updates.length<=12&&Array.isArray(ev.observations)&&ev.observations.length<=4&&ev.observations.every(v=>text(v,300)),'evolution');const paused=d.needed||outcomes.some(e=>['partial','clarify'].includes(e.status));if(paused||ev.basis==='none')assert(!ev.updates.length&&!ev.observations.length,'paused evolution');else assert(outcomes.some(e=>e.beat===ev.basis),'evolution cause');
  for(const u of ev.updates){const e=s.entities.find(v=>v.id===u.id);assert(e&&e.integrity!=='consumed'&&text(u.facts,700)&&text(u.reason,400)&&['intact','damaged','consumed'].includes(u.integrity),'evolution facts');assert(!(e.integrity==='damaged'&&u.integrity==='intact'),'evolution repair');assert(u.integrity!=='consumed'||(e.movable&&e.kind!=='npc'),'evolution protected entity');if(u.integrity==='consumed'){e.lastPlace=physical(e,s);e.place='consumed';}e.facts=u.facts;e.integrity=u.integrity;e.updatedAtRevision=s.revision+1;}
  recordObservations(s,ev.observations,s.revision+1,'observed_evolution');
  // Scene membership alone does not disclose hidden contents or NPC secrets.
  // Public records change only with host-confirmed observation or direct action.
  for(const e of s.entities)if(e.place==='carried')s.knownEntities[e.id]=structuredClone(e);
  s.pendingDecision=s.status==='ended'?null:d.disposition==='keep'?structuredClone(original.pendingDecision):d.needed?{...d,intent:p.intent,originalAction:action}:null;
  applyMemories(s,p.memory_updates||[],action,outcomes,s.revision+1);s.revision++;s.turn=s.revision;s.log.push({role:'player',turn:s.turn,text:action});s.events.push({revision:s.revision,intent:p.intent,steps:outcomes,evolution:ev});return {state:s,outcomes,evolution:ev};
 }
 return {MAX_TURNS:null,createGame,normalizeGame,getActions,getView,hostContext,applyProposal};
}
