// Adapted with publication permission confirmed by the site owner, 2026-09-21.
// Original author: 梅姐. NOT CC licensed. No original DOCX or map artwork here.
const object=(id,name,place,facts,nature,movable=true)=>({id,name,place,facts,nature,movable,kind:'object',integrity:'intact',source:null});
const person=(id,name,place,facts,nature)=>({...object(id,name,place,facts,nature),kind:'npc'});
const room=(name,description,exits)=>({name,description,exits});
const milestone=(places,refsAny,rule,extra={})=>({places,refsAny,rule,...extra});
const effect=(id,set,extra={})=>({id,set,...extra});
const rights={author:'梅姐',source:null,license:null,publication:'author-permitted',publicScenario:false,licenseText:'原作著作权归梅姐所有。本次改编与公开发布已获作者许可；本页不授予再次转载或改编的许可。',pace:'剧情阶段推进',allowLeaveAtStart:false};

export const meijieStories={
 'bindi-shang':{
  ...rights,id:'bindi-shang',title:'并蒂殇',original:'并蒂殇',start:'hotel',
  tagline:'相同的面容，能否成为同一个人的证词？',summary:'生日宴前，一名侍从死在酒店。你受托调查神定家的秘密：两张相似的面孔、一段被抹去的往事，以及尚有机会阻止的下一桩悲剧。',tags:['现代悬疑','身份迷局','调查与营救'],
  opening:'你是一名受邀参加神定家生日宴的侦探。昨晚，神里大酒店还回响着碰杯声，主人神定舒元客气地与你寒暄，说几天后的生日宴才是重头戏。你与同桌一位戴口罩的黑发姑娘只说过几句话，尚未来得及知道她的姓名。今晨，客房电话却把你从睡梦中叫醒：十三楼出事了，酒店希望你协助调查。\n\n你来到大堂。早餐已经撤下，几名宾客压低声音交谈；神定家的侍从小冯被发现死在自己的房间里。前台确认，你可以进入现场查看，但请尽量保留原状。电梯仍在运行，楼上有人守着房门。此刻你还不知道死因，更不能仅凭客人的猜测认定谁是凶手。\n\n昨晚的黑发姑娘站在窗边，手指攥着手机，似乎想开口又有所顾虑。神定舒元正在另一边安抚宾客，一位被人称作大刘的中年商人则独自坐着，几次看向通往楼上的电梯。大堂外可以叫车前往神定家的宅邸，但那里的私人楼层是否允许你进入，还需要交涉。\n\n你带着手机、便笺本和一支小手电。手机能够拍照、查询公开资料与保存实际取得的证据，不会替你破解所有秘密。眼下可以先去十三楼确认现场，向前台核对昨夜的房卡记录，也可以找窗边的姑娘或大刘聊聊。你可以暂时不下结论；把看见的痕迹、听到的说法和自己的推测分开，会比急着找一个嫌疑人更有用。',
  places:{
   hotel:room('神里酒店大堂','宴会暂歇，电梯旁有人低声议论。前台可核对房卡记录，窗边可私下交谈。',['crime','guest','mansion','oldhouse','records','police']),
   crime:room('十三楼现场','单人间已获准勘查；洗手间与床铺之间没有明显的大规模搏斗痕迹。',['hotel']),
   guest:room('黑发姑娘的客房','一间普通客房；房门与入住记录需要合理取得访问许可。',['hotel']),
   mansion:room('神定宅邸一层','华丽客厅连着厨房和楼梯，私人楼层由侍从照看。',['hotel','garden','landing']),
   garden:room('宅邸花园','花坛贴着宅邸外墙，向上可见二层露台。',['mansion']),
   landing:room('二层小客厅','走廊两侧是卧室，楼上还有露台花园。',['mansion','sister_room','study','roof']),
   sister_room:room('天宁的卧室','卧室连着露台，窗边挂着浅色床单。',['landing']),
   study:room('舒元的卧室与书桌','电脑在书桌上，床头柜靠墙，私人文件需要合法授权或承担潜入风险。',['landing','cellar']),
   cellar:room('隐蔽房间','梯子通向一层内部的狭窄空间；这里与外面的客厅被厚墙隔开。',['study']),
   roof:room('三层花园','半露天花园，楼下庭院的声音偶尔传来。',['landing']),
   oldhouse:room('姐妹旧宅','郊区的两层旧屋，窗边长满杂草，照片仍留在客厅。',['hotel']),
   records:room('公共资料室','旧报刊、企业公开资料与可申请调阅的记录在这里汇集。',['hotel']),
   police:room('警方接洽处','可以提交已取得的证据、申请核查和保护；猜测不能代替来源。',['hotel'])
  },
  gates:[{a:'mansion',b:'landing',flag:'upstairs'},{a:'study',b:'cellar',flag:'cellar_access',hidden:true}],
  entities:[
   object('phone','手机','carried','可以拍照和通话，尚无案件证据副本。','只能保存实际见到的材料；公开搜索、询问与受授权的邮件访问可用。不凭一句破解取得机密。'),
   object('journal','便笺本','carried','空白页充足。','记录真实调查与约定的纸本。'),object('torch','小手电','carried','完好。','普通电池手电，无明火。'),
   person('haiming','戴口罩的黑发姑娘','hotel','黑发盘起，戴口罩，欲言又止。','真实身份是神定海茗，妹妹，染黑白发，冷静，有复仇意图。合理取得信任后交换姓名、手机号，邀请调查宅邸；不初见就交代所有计划。'),
   person('tianning','神定天宁','sister_room','白发散落，独处卧室，对陌生人保持距离。','姐姐，常年受压迫。她杀死虐待自己的小冯，伪装侍女入酒店。后来为阻止妹妹复仇，迷晕并藏起妹妹、假扮妹妹。被识破可坦白并求帮助；保护不等于赦免第一起命案。'),
   person('uncle','神定舒元','hotel','客气地安抚宾客，言谈体面。','叔父，十年前出卖姐妹父母，现图谋遗产。本版统一为幕后雇凶者，杀手执行；不会无证据就承认。掌握宅邸访问权限，知道自己生日。'),
   person('liu','大刘','hotel','独坐一侧，显得心事重重。','商业伙伴、姐妹父母旧识。适合私聊，可讲公司更替和父母遇害背景，提示旧邮箱存在，但不能直接给出定罪证据。'),
   person('butler','老黄','mansion','守着会客厅与楼梯，对宾客礼貌而严厉。','管家，严厉控制家中仆人；侍从忌惮他，可能受证据与主人授权影响。'),
   person('maid','茜茜','mansion','正在收拾，话很少。','被小冯欺负，曾想报复但不是凶手。可在得到安全保障后提供管教、服装和作息线索。'),
   person('assassin','陌生男子','roof','暂未与玩家接触。','受舒元雇用的持刀杀手。只有 murder_window 才实际进入密室袭击；未触发前在三楼伪装维修人员，可调查可提前制止，不能凭姓名知道身份。'),
   object('body','小冯的遗体','crime','伏在洗手台旁，现场尚待勘查。','背部致命伤不利落，像熟人趁背身下手。勘查只能形成有限推断，不直接点名凶手。',false),
   object('bow','侍女服领结','crime','浴帘边缘有一角布料露出。','沾有小冯血液，是天宁伪装时遗落，必须检查才揭露血迹和样式。'),
   object('victim_notes','小冯的随身笔记','crime','在死者衣袋里。','记着对天宁的管教和对两名侍女的责骂，非直接认罪书。'),
   object('keylog','房卡记录','hotel','前台可以协助查阅相关时间的登记。','案发前有侍女领走房卡，不足以单独确认姓名。',false),
   object('room_card','房卡与衣物','guest','房内有衣物和房卡夹，需获得许可或说明进入办法。','房卡夹写海茗真实姓名和房号；手机号码须由本人交换。房间不因玩家知道名字自动开门。',false),
   object('servant_note','水槽下的纸条','mansion','厨房管路下夹着折纸。','两名侍从谋划报复管家，未说杀人；可用于交涉上楼，不可当命案证据。'),
   object('sheet','窗边床单','sister_room','浅色床单垂在床边。','有系绳拉扯裂痕，可与花园脚印和酒店领结相互核对。'),
   object('prints','花坛脚印','garden','窗下的泥土有踩踏痕迹。','能提示有人夜间翻窗，模糊鞋印不能直接确定身份。',false),
   object('computer','舒元的电脑','study','登录页锁着，垃圾桶里有画圈日期的旧日历。','本机密码为舒元生日，日历可给线索；本机只有宅邸图与密室控制链接，不直接存谋杀计划。已获得邮箱线索后才可访问邮件，不能混同本机文件。',false),
   object('hatch','床头柜下的暗门','study','柜脚周围有反复拖移痕迹。','电子入口需电脑控制链接与密码或知情人帮助；只推开柜子不算打开。',false),
   object('diary','父母旧日记','oldhouse','一本褪色笔记留在床下。','怀疑舒元勾结敌对公司，并提到父母邮箱草稿；合影、旧报刊可核对姐妹生日。'),
   object('old_mail','父母邮箱草稿与往来','oldhouse','旧宅书桌可用随身手机访问已查明的邮箱。','账户从日记或公开资料获得，密码为姐妹生日。草稿指向旧邮箱交易；需保留原邮件并向对方公司核验，推测不足以定罪。',false),
   object('case_mail','舒元邮箱与通联记录','study','需通过实际取得的账号访问或申请警方依法调取。','保留雇凶交谈及联络线索。与杀手口供、号码来源和真实往来核验后可证明现案；不得凭本机登录直接拿到全部邮件。',false),
   object('knife','杀手的刀','roof','由陌生男子隐蔽携带。','并非小冯案凶器；实际制服或对峙后才能取得，与妹妹衣物血迹有区别。'),
  ],
  companions:[{id:'haiming',requires:['partner'],excludes:['separated']},{id:'tianning',requires:['disguise'],excludes:['murder_window','sisters_safe']}],
  milestones:{
   partner:milestone(['hotel'],['haiming'],'私下建立基本信任，海茗介绍自己、交换联系方式，自愿一同调查；必须更新她的已公开身份与手机记录。'),
   first_evidence:milestone(['crime'],['bow','body','victim_notes'],'实际勘查并记录至少两个互相关联的现场发现；不能仅看一眼就指认凶手。'),
   family_lead:milestone(['hotel','records','oldhouse'],['liu','diary'],'通过大刘、资料或日记获知姐妹父母和集团更替的关联，知道旧宅调查方向。'),
   upstairs:milestone(['mansion'],['butler','maid','servant_note'],'交涉获准、用真实线索说服侍从或完成合理潜入后取得上楼通路；单说我要上楼不算。'),
   cellar_access:milestone(['study'],['computer','hatch','tianning'],'实际打开电子暗门：找到控制链接和有效密码，或让知情的天宁在场协助；不能移开柜子就获得密码。'),
   old_evidence:milestone(['oldhouse','records','police'],['old_mail','diary','phone'],'实际取得并保存父母邮箱往来，与对方公司或官方记录核对；日记中的怀疑不是结论。',{requires:['family_lead']}),
   separated:milestone(['hotel','mansion'],['haiming'],'玩家在完成初步调查后明确同意与海茗分头、或自行回房过夜；若正在护送、盯守、跟踪她则禁止强制失踪。告知她有自己的调查，不替玩家同意。',{requires:['partner','first_evidence'],excludes:['sisters_safe'],effects:[effect('haiming',{place:'cellar',facts:'失去意识后被束缚在隐蔽房间。'},{from:['hotel','mansion']})]}),
   disguise:milestone(['hotel'],['phone'],'分开之后玩家明确继续次日调查或回酒店赴约；一位自称海茗的黑发姑娘找来劝其休息，不向玩家揭露真身。',{beats:['action','wait'],requires:['separated'],excludes:['sisters_safe'],effects:[effect('tianning',{place:'hotel',name:'自称海茗的黑发姑娘',facts:'黑发盘起，没戴口罩，带着手机，劝你享受宴会。'},{from:['sister_room']})]}),
   disguise_found:milestone(['hotel','crime','guest','mansion','garden','landing','sister_room','study','roof','oldhouse','records','police'],['tianning','phone','room_card'],'实际比对原手机号、房号或两部手机等可验证破绽，并当面让天宁承认；单凭更活泼或猜测不算证实。',{requires:['disguise'],effects:[effect('tianning',{name:'神定天宁',facts:'身份被识破，承认曾替代妹妹；接下来的信任需交谈建立。'},{visible:true})]}),
   murder_window:milestone(['hotel','mansion','landing','study','cellar','sister_room'],['tianning','haiming','assassin'],'玩家明确跟随天宁去隐蔽房间，或自行赴宅邸调查姐妹危险后启动对峙场景。必须给出可感知的动静和干预机会；本标记不造成死亡。',{requires:['separated'],excludes:['sisters_safe','tragedy'],effects:[effect('tianning',{place:'cellar',name:'神定天宁',facts:'在隐蔽房间面对挣脱束缚的海茗。'}),effect('haiming',{place:'cellar',facts:'已经挣脱束缚，与姐姐对峙，迟疑着放下手中的刀。'}),effect('assassin',{place:'cellar',facts:'持刀进入，试图袭击姐妹。'},{from:['roof']}),effect('knife',{place:'cellar',facts:'仍由杀手持有。'},{from:['roof']})]}),
   sisters_safe:milestone(['cellar','roof','sister_room','study'],['tianning','haiming','assassin'],'实际保护两姐妹并制止杀手，或提前揭露雇凶并获得有效保护使袭击无法实施。不能只作口头承诺；危险解除、人员位置和约定需写清。',{excludes:['tragedy']}),
   tragedy:milestone(['hotel','mansion','study','cellar'],['assassin','tianning'],'仅在危险已经明确告知且玩家明确放弃营救、离开或长时间等待后结算天宁遇害；询问、检查或短暂尝试不能触发，成功保护绝不覆盖。',{requires:['murder_window'],excludes:['sisters_safe'],effects:[effect('tianning',{place:'cellar',facts:'被杀手杀害，遗体仍在现场。'}),effect('haiming',{place:'cellar',facts:'被击昏，衣物被人为沾上血迹。'}),effect('assassin',{place:'roof',facts:'已撤离密室，试图离开宅邸。'})]}),
   exonerated:milestone(['cellar','police'],['haiming','knife','phone'],'通过真实血迹、凶器和通联等材料排除海茗杀害天宁的嫌疑，不能靠相信她；警方核查结论需有来源。',{requires:['tragedy']}),
   present_evidence:milestone(['study','cellar','roof','police'],['case_mail','assassin','phone'],'实际取得、保存并核验雇凶往来或杀手证词与通联记录，足以指向舒元；只有动机不算证据。'),
   submitted:milestone(['police'],['phone','journal'],'玩家明确将所持证据、原始出处和证言交给警方，要求立案与必要保护；只打听办案流程不算提交。')
  },
  endings:{
   both:{title:'并蒂未折',text:'你把两姐妹带到了能够获得保护的地方。她们都还活着；保护她们与查清小冯之死，是两件同样需要继续面对的事。叔父是否被追责，以你实际提交的证据为准。',places:['police'],requires:['sisters_safe','submitted'],excludes:['tragedy']},
   full:{title:'十年回声',text:'你交出了现案与旧案相互印证的证据，警方开始追查舒元。迟来的真相没有抹去已经发生的伤害；它终于不再只是一家人的沉默。',places:['police'],requires:['old_evidence','present_evidence','submitted']},
   justice:{title:'不再无声',text:'雇凶证据进入正式调查，舒元体面的外衣出现了无法掩盖的裂口。旧案仍需要更多核验；你没有把尚未证实的推测冒充结论。',places:['police'],requires:['present_evidence','submitted']},
   innocence:{title:'未竟的清白',text:'你交出的材料洗清了海茗的嫌疑，但尚不足以让幕后主使承担责任。清白得到了保留，追查还没有结束。',places:['police'],requires:['exonerated','submitted'],excludes:['present_evidence']},
   unresolved:{title:'留在卷宗里的疑问',text:'你结束了此次调查，把已经确认的材料交给警方。缺失的证据仍留下疑问，谁也不能把你的怀疑当成已经得到的判决。',places:['police'],requires:['submitted']}
  },
  suggestions:[{id:'next_day',label:'结束今天的初步调查，与海茗约好分头行动，回酒店休息',places:['hotel'],requires:['partner','first_evidence'],excludes:['separated','sisters_safe']},{id:'meet_again',label:'继续次日调查，看看酒店有没有新的消息',places:['hotel'],requires:['separated'],excludes:['disguise','sisters_safe']}],
  laws:['这是保留核心真相的事件阶段改编，开局从小冯案翌晨开始，生日宴作为回忆；不按输入条数推进日期。下一阶段必须由玩家明确分头、赴约、休息或进入危险现场推动。','NPC真实身份、外表和玩家所知分开。tianning假扮妹妹时，未disguise_found前叙述只称自称海茗的姑娘，不泄露真实姓名。原始nature是主持秘密。','玩家承诺看守、护送或先行保护时，不许强行迷晕海茗、挪走天宁或制造必死剧情。提前截断阴谋允许姐妹双活；同伴自行离开必须有当场可知的原因和回应机会。','杀手执行、叔父雇凶为本版统一解释。第一起小冯命案由天宁实施，叔父现案证据不能证明他杀了小冯；天宁获救不免除调查。','所有后台远处移动仅在milestone.effects生效，不用evolution瞬移。袭击窗口只在可回应危险出现时开启，未知密室不能直接出现在公开地图。','警方通联调取、邮件核验需要玩家提交已获线索。获取证据和交给警方是不同步骤；不能用推理自动生成一封认罪邮件。','手机只处理玩家实际有号码的人与已有材料；远程通话可记为观察，不用updates修改远处NPC。不把未接电话解释成已知绑架。','公共资料室和警方接洽处是本版合并的服务场景，旧宅路程按叙事描述，不扣机械时限。结束需玩家明确提交结案或离场，不能自动替玩家决定。'],
  changes:'从原稿第一幕命案调查切入，宴会压缩为开场回忆；宅邸与取证地点合并为13处场景。日期推进改为玩家触发的调查阶段，取消两动作死亡窗口；保留双生身份、现案与旧案证据链、提前营救分支。统一叔父雇凶、杀手执行。省略数值战斗与恋爱好感检定，不重现原稿全部结局措辞；提前保护可改变后续事件。未使用原稿地图美术。'
 },
 'downtown-island':{
  ...rights,id:'downtown-island',title:'市中心的孤岛',original:'市中心的孤岛',start:'home',
  tagline:'广播说，救援很快就到。你愿意相信吗？',summary:'病毒让熟悉的街道成为孤岛。寻找补给，认识一个来历不明的白发女孩，在实验室和封锁线之间查明真相，决定如何离开这座城市。',tags:['灾变生存','同伴关系','真相与撤离'],
  opening:'你不是为灾难做足准备的探险家，只是住在市中心十层公寓里的一名普通居民。几天前，你还在为工作和账单发愁。现在，楼下道路被路障截断，偶尔传来的尖叫让你不敢轻易拉开窗帘。你躲过了最初的混乱，却不知道熟悉的邻居还有多少人平安。\n\n收音机里，官方反复播送同一段消息：救援正在组织，特效药正在研制，请居民留在安全地点等待。它还声称怪物只能存活七天。声音平稳得令人想要相信，但你没有亲眼见过救援队，也没有办法核实那句保证。网络此刻仍能连接，手机上的消息真假混杂。\n\n你重新清点了厨房：四份简餐，足够一个人正常吃上两天；饮水暂时能取得。桌上放着手电、胶带和一把普通螺丝刀，床上有可以利用的床单。你没有枪，也不是突然就会应付一切的战士。房门外是十层走廊，电梯旁有楼梯间；去楼下查看、敲门找邻居或先听清广播，都需要由你自己决定。\n\n眼下最直接的问题，是找到能维持生活的补给，并弄清楼里是否还有安全的出路。可以先用猫眼和手机了解近处情况，再带上工具试探走廊；也可以检查屋内能派上用场的东西。这里不会因你多问一句就扣去一天，实际进食、长时间休息与危险行动才留下后果。至于广播里的希望是否可靠，或许要等你走到门外，才有机会找到自己的答案。',
  places:{home:room('十层的家','门窗暂时完整，厨房与收音机仍可使用。',['hall']),hall:room('公寓楼梯间','十层走廊连着楼梯，部分空置房门开着。楼梯通向楼门和地下室。',['home','lobby','basement']),lobby:room('一楼门厅','玻璃门从外侧被U形锁锁住，附近没有明显的安全出口。',['hall','street']),basement:room('地下室出口','厚金属门由磁锁控制，可查配电线路与通风口。',['hall','street']),street:room('封锁街区','路障、停驶车辆与残破招牌之间仍有小路可走。',['lobby','basement','shop','pit','camp','lab_a','government','garage']),shop:room('临街小商铺','卷帘门半掩，有人摆出少量可交换的物资。',['street']),pit:room('旧试验场与尸坑','围栏有缺口，工棚在外围；更深处空气污浊。',['street']),camp:room('体育场隔离营','广播指引人们登记，围栏内有食物与检测站，出口由人看守。',['street']),lab_a:room('实验室A区','收容区，终端和门边标识仍可辨认。',['street','lab_b','lab_c']),lab_b:room('实验室B区','办公、档案与生活区域，部分房门锁着。',['lab_a','lab_c']),lab_c:room('实验室C区','小型生活空间与更深处的设备室相连。',['lab_a','lab_b','omega']),omega:room('心灵放大装置室','核心装置的控制台要求更高级别授权。',['lab_c']),government:room('政府大楼一层','登记台、食堂与楼梯，人员往来仍然有序。',['street','government_two']),government_two:room('政府大楼二层','会议室、储物间和监控室；走廊存在巡逻。',['government','government_three']),government_three:room('政府大楼三层','高级办公室、资料室与正在使用的会议室。',['government_two','helipad']),helipad:room('楼顶停机坪','屋顶有停机标识，通道通向三层；是否有可用直升机取决于实际接洽。',['government_three']),garage:room('修车铺与出城道路','一辆越野车停在卷帘门后，前方道路通向封锁线。',['street'])},
  gates:[{a:'lobby',b:'street',flag:'front_exit'},{a:'basement',b:'street',flag:'basement_exit'},{a:'lab_a',b:'lab_b',flag:'level_one'},{a:'lab_c',b:'lab_b',flag:'level_one'},{a:'lab_c',b:'omega',flag:'level_three'},{a:'government',b:'government_two',flag:'gov_access'}],
  entities:[
   object('phone','手机','carried','电量足够当前使用，网络仍可连接。','可记录材料、查询公共信息，无万能破解功能。'),object('torch','手电','home','完好，有电。','电池手电，无明火。'),object('tape','胶带','home','尚未使用的一卷。','普通家用胶带，可固定和封装。'),object('driver','螺丝刀','home','普通手动工具。','可拆家用螺丝，不能撬开全部电子锁。'),object('sheet','床单','home','干净结实。','可捆扎；十层不能凭一条床单安全垂降，低层借固定点才可讨论。'),
   object('food','家中简餐','home','完整4餐份。','食用、分享才减少，并在facts保留具体剩余餐份；转移不改变数量。真实过夜通常玩家2份、同行玲衣1份；无食物只先呈现饥饿与选择，绝不凭空立刻饿死。'),
   object('radio','收音机','home','持续播报官方消息。','七天存活保证是政府说辞，不等于世界已证实的规律。'),object('lock','楼门U形锁','lobby','从外侧锁住玻璃门。','需要真实工具破拆，或对巡视者交涉；可从低层合适窗户和床单寻找另一出口，但十层不可直接跳出。',false),object('power','地下室磁锁配电箱','basement','金属门锁闭，配电回路可以查看。','可在确认线路后切断本地磁锁供电打开；这是本版可行动的备用出口，不必等第三天。',false),
   object('hall_food','邻居留下的食品','hall','空置房厨房中有封好的包装。','实际检查可找到2餐份，不无限刷新。'),person('trader','幸存摊主','shop','警惕地守着小摊，接受合理交换。','知道尸坑位置、工棚疫苗传闻和隔离营食宿；不知完整阴谋。'),object('shop_food','摊位上的补给','shop','归摊主所有，尚未交换。','共6餐份，交换或取得有后果；取走后不能刷新。'),
   person('lingyi','白发女孩','pit','躲在工棚背风处，不愿靠近制服人员。','实验品01，名字玲衣，心智单纯而警惕，有心灵与念动力能力。对力量效果缺少理解但能较好控制，需尊重自愿；能力使用需要休息和补给，不是万能开锁器。知道C区生活空间，可回忆一级密码。'),
   object('pit_records','工棚记录与铭牌','pit','工棚有实验机构标识，散落着记录。','外围可查地址和试验场痕迹；坑内才有玲衣铭牌和强化剂，不把所有奖励放在门口。',false),object('suppressant','普通疫苗','pit','工棚冷藏箱里有一份封存制剂。','只能压制症状，非治愈；需查说明与保存状态，不是完美疫苗。'),object('pit_food','工棚食品','pit','封存柜中有少量补给。','完整2餐份，需实际寻找。'),object('enhancer','强化剂','pit','在尸坑深处的防护箱内，尚未取得。','与普通疫苗不同，实际取得且经说明核验后可供玲衣自愿使用，降低她的能量负担；不能无视感染风险远程取出。'),
   person('guard','隔离营值班人员','camp','要求登记和血液检测，禁止随意离营。','营地提供食宿，却在筛选试验对象。对玲衣的本能恐惧不等于已经知道身份。离营需真实交涉或规避，不能锁门后仍自由走出。'),object('camp_log','检测与调度记录','camp','检测站内有登记表，只有部分可见。','可发现受检者被转往研究设施的可核实线索，完整政府阴谋仍需进一步证据。',false),
   object('terminal_a','A区终端','lab_a','本区地图可公开调阅，门禁要求授权。','员工值班本夹着一级密码线索；一区终端只控制一区门禁。',false),person('researcher','被困研究员','lab_b','在办公室内呼救，门外有危险收容体。','获救并达成可信交易后愿给二级、三级权限和研究解释；不是仅问一句就全交。怕玲衣，知道政府研究合作。'),object('archive','实验档案','lab_b','档案柜和工作终端尚待检查。','研究目的为改造人类基因，政府将平民作为材料；普通疫苗抑制、完美疫苗治愈的区别可查明。复制需实际操作保存到手机。',false),object('c_room','C区生活记录','lab_c','床边有编号01的痕迹。','玲衣实际回到这里可回忆一级密码；不证明她是危险敌人，也不授权玩家强迫她。',false),object('amplifier','心灵放大装置','omega','待机，尚未获使用许可。','需三级权限与玲衣本人明确愿意，能提供设施与幸存者信息、样本位置和武器柜密码；不会控制全城或消除感染。',false),object('sample','玲衣的封存样本','lab_c','制备室柜体内，位置和权限尚未知。','需三级授权及放大装置揭示或实际仔细调查定位；样本只是研究材料，不能自动复活或制造万能药。'),
   person('executive','实验室高管','government_three','与市政人员闭门交谈，手边有冷藏箱。','掌握完美疫苗和研究秘密；可以通过证据、交换或实际胁迫谈判，绝不见面赠送。接到警报时准备撤离，给玩家响应窗口，不凭闲聊轮数消失。'),object('meeting_notes','会议资料','government_two','会议桌抽屉有几页遗漏的资料。','明确记载拿平民作试验的合作与转运安排，可拍照保存。',false),object('research_notes','隐藏研究资料','government_three','资料室内部另有受保护的柜体。','高级办公室的真实平面图可定位，需实际查找才能取得；完整研究也不让无医学知识的玩家立即造出超人。',false),object('cure','完美疫苗','government_three','由高管保管的冷藏箱中，尚未取得。','有效治愈并提供该毒株免疫，须有真实交易或夺取，检查封存和剂量；一份制剂一次使用，不能同时治疗所有人。'),object('gov_food','食堂储备','government','封存在食堂仓储架上。','可取得6餐份；是否获准、取走多少和后果须明确，不能无限补充。'),
   object('car','越野车','garage','车体基本完整，尚未检查。','可检查车钥匙、发动机和油量，发动机可用但油量不足以通过封锁区；加足油后无需因没查真相而强制断油。',false),object('garage_key','工具间钥匙','garage','藏在柜台抽屉最内侧，尚未被发现。','实际检查柜台抽屉可找到的普通机械钥匙，匹配工具间门锁。寻找是有明确位置的固定线索，不是临时生成万能钥匙。'),object('fuel','备用油桶','garage','在上锁的工具间内。','有足够一次出城的汽油，需实际开门取得并加注。消耗后不可重复用。'),object('helicopter','撤离直升机','helipad','停机坪设有联络标识，尚未获得登机安排。','联络批准后才能登机；政府路线有洗脑控制意图，先查到证据可尝试识破、谈判或拒绝。',false)
  ],
  companions:[{id:'lingyi',requires:['companion'],excludes:['parted']}],
  milestones:{
   front_exit:milestone(['lobby','hall'],['lock','sheet','driver'],'实际破开楼门锁、说服巡视者开门或从安全低层路线到达外侧解锁；不许十层无保护跳跃。'),
   basement_exit:milestone(['basement'],['power','driver'],'确认本地磁锁回路并安全断开供电，实际解除厚门锁；无须等到第三天。'),
   companion:milestone(['pit'],['lingyi'],'发现女孩后通过交谈和实际善意建立基本信任，她自愿同行，名字玲衣由她告知；必须记录约定，不要求交出食物才给她人格。'),
   trust:milestone(['pit','street','home','hall','lobby','basement','shop','camp','lab_a','lab_b','lab_c','omega','government','government_two','government_three','helipad','garage'],['lingyi'],'经实际尊重、保护或分享建立稳定互信，并明确与玲衣讨论共同离开的意愿；一句跟我走不能自动达成。',{requires:['companion'],excludes:['parted']}),
   parted:milestone(['pit','street','home','hall','shop','camp','lab_a','lab_b','lab_c','omega','government','government_two','government_three','helipad','garage'],['lingyi'],'玩家明确让玲衣在安全地点留下，或严重背弃约定使她拒绝继续同行；需要当面表达和可回应机会，不能默默丢下。',{requires:['companion']}),
   level_one:milestone(['lab_a','lab_c'],['terminal_a','lingyi','c_room'],'实际从值班本找到一级密码或玲衣在C区回忆后自愿告知，并在终端验证有效。'),
   level_two:milestone(['lab_b','government_three'],['researcher','executive'],'实际帮助或与合资格研究人员达成交易后取得并验证二级权限，控制对应区域机枪，不靠猜谜编密码。',{requires:['level_one']}),
   level_three:milestone(['lab_b','government_three'],['researcher','executive'],'在可信交涉或有实效的手段下取得三级权限，了解装置风险，不能以一级授权代替。',{requires:['level_two']}),
   amplified:milestone(['omega'],['lingyi','amplifier'],'玲衣同房、自愿同意且完成准备后实际启用装置；记录她的疲劳和补给需求，揭示实验室地图、样本位置和武器密码而非无边界超能力。',{requires:['level_three','companion'],excludes:['parted'],entityRules:[{id:'lingyi',place:'omega'}]}),
   lab_truth:milestone(['lab_b'],['archive','phone'],'实际阅读实验目的、感染与疫苗记录并复制保存，确认研究不是普通救灾。',{entityRules:[{id:'phone',place:'carried',intact:true}]}),
   gov_access:milestone(['government'],['phone','guard'],'实际取得楼上通行许可、找到已观察的巡逻空隙或执行合理潜入；不是念出要上楼就成功。'),
   government_truth:milestone(['government_two','government_three'],['meeting_notes','research_notes','phone'],'取得并保存平民实验与转运合作证据；见到制服或听信传闻不能算查明。',{entityRules:[{id:'phone',place:'carried',intact:true}]}),
   cured:milestone(['home','pit','camp','lab_a','lab_b','lab_c','omega','government','government_two','government_three','helipad','garage','street'],['cure'],'实际获得完美疫苗，核验并按说明为玩家使用，更新制剂消耗；不能把普通疫苗当治愈。',{entityRules:[{id:'cure',place:'consumed'}]}),
   car_ready:milestone(['garage'],['car','fuel'],'实际检查和启动车辆，将足够汽油加注，更新油桶为已消耗；地图上看到车辆不算准备完成。',{entityRules:[{id:'fuel',place:'consumed'}]}),
   flight_ready:milestone(['government','government_three','helipad'],['helicopter','executive','phone'],'实际通过可用联络、谈判或有效控制取得撤离登机安排，尚不代表玩家同意登机。'),
   flight_compromise:milestone(['helipad'],['helicopter','lingyi'],'已实际登机后发现政府控制企图，明确危险和玩家应对；仅选择登机前先问风险不能触发失控。',{requires:['flight_ready'],effects:[]})
  },
  endings:{
   together:{title:'驶向未明的天光',text:'你和玲衣驶离封锁区。已经检查的车和足够的燃油支持了这次出发；带走多少真相、是否获得治愈，取决于你真正完成的调查。未来尚未确定，但这条路是你们共同选择的。',places:['garage'],requires:['car_ready','trust'],excludes:['parted'],entityRules:[{id:'lingyi',place:'garage'}]},
   road:{title:'公路另一端',text:'你驾车离开了城市。油量与车辆状态经过实际准备；同行与留下的人，都依照离开前真实达成的选择。尚未查明的秘密仍留在身后。',places:['garage'],requires:['car_ready']},
   informed_flight:{title:'带着证据登机',text:'你带着已经保存的证据踏上争取到的撤离路线。你知道这趟航程背后还有控制与隐瞒，离开城市只是下一段交涉的开始。',places:['helipad'],requires:['flight_ready','government_truth'],entityRules:[{id:'phone',place:'carried',intact:true}]},
   flight:{title:'广播的另一端',text:'你选择乘政府安排的直升机离开。机舱里开始出现与救援广播不同的要求；你获得了离开城市的机会，却还没有知道承诺背后的全部代价。',places:['helipad'],requires:['flight_ready'],excludes:['government_truth']},
   shelter:{title:'暂时的屋檐',text:'你决定留在隔离营，暂以食宿与秩序换取安全。这不是病毒已经结束的证明，而是你此刻选择停下来的地方。',places:['camp']},
   research:{title:'留下来的人',text:'你暂缓撤离，把取得的研究与样本交给愿意合作的专业人员。研究尚需时间和验证，任何人都没有因此立刻成为不朽的新人类。',places:['lab_b'],requires:['lab_truth','government_truth','level_three'],entityRules:[{id:'sample',place:'carried'},{id:'cure',place:'carried'},{id:'researcher',place:'lab_b'}]}
  },
  suggestions:[],
  laws:['本版是城市探索与关系选择改编，七天日历压缩为行动触发的阶段；不做每轮耗餐、随机感染累积或固定日终死亡。广播七天说法只是传闻。原稿数值生存模拟和超人/复活灭世结局不在本版。','家中起始4餐，其他食品有固定来源与数量。只有实际进食、明确过夜或使用能力才结算消耗，facts保留剩余餐份，不因来回询问扣食物。玲衣同行过夜1餐，实际用能力后额外2餐一次；不把能力代价重复按消息扣除。无法满足先呈现疲劳和选择，不能突然死亡。','离营、感染与追捕由真实行动产生，先说明可察觉风险。普通疫苗仅抑制，完美疫苗才治愈。感染不是隐藏倒计时；症状、接触源与处理写进状态，不用没有发生的随机检定宣判变异。','玲衣的能力、加入、研究取样均需她明确自愿。她可拒绝，信任通过真实事件建立，不允许用一句夸奖跳过共同经历。随行由程序沿相邻路线移动，失散不能瞬移；未companion时她留在尸坑，不在家门口再生成第二个女孩。','隔离营被合并为一处。警戒、登记与离营限制要写进guard.facts；玩家未经真实交涉或规避不能仅凭地图连接出营。不要把人类守卫讲成无条件敌人。','政府人员接到报警可开始撤离，但必须呈现可知动静与响应机会；玩家继续等待、主动放弃才离开。不使用一小时/三小时按输入数折算。伏击、跨城、长劳动遇到新危险先停下交还选择。','取用pit深处的强化剂、别人的食物、高管疫苗需要真实可行的行动，实体同房不是免费可拿。完美疫苗与样本不是万能解药配方，原稿的夸张Ex结局改为开放研究收束。','驾车结局必须真有足够燃油，但缺少政府真相不再强制断油；本人拒绝登机就不自动触发坠机。直升机结局在离城选择处收束，不强迫玲衣牺牲。选择留营或研究仅玩家明确结束时收束。','普通家用物品可合理利用；武器不凭空生成，本版未开放原稿军火库支线。房间、固定证据和NPC身份不因主持需要而漂移。'],
  changes:'合并隔离营与住宅楼房间，保留17处探索场景、实验室三级权限、玲衣同行、两种疫苗和车辆准备。七日时间表改为行动推动的阶段，不复刻数值饥饿、随机感染或按时间触发的强制死亡；增加可主动切断的地下室磁锁回路。明确燃油与知情程度互不替代；直升机在离城选择处收束，不强制牺牲同伴，超人/复活灭世支线改为开放研究结局。省略军火库支线。未使用原稿地图美术。'
 }
};
