import {meijieStories} from './meijie-stories.js';
// Koa-OL Chinese single-player adaptations. License is specified per story.
// Full attribution and change notes are published with each scenario.
const entity=(id,name,nature,place,facts,movable=true,kind='object')=>({id,name,nature,place,facts,movable,kind,integrity:'intact',source:null});
const npc=(id,name,place,facts,nature)=>entity(id,name,nature,place,facts,true,'npc');
const room=(name,description,exits)=>({name,description,exits});
const common=[entity('light','提灯','普通有热量的油灯，可打开灯罩；不模拟燃油倒计时。','carried','完好，亮着。'),entity('rope','绳索','普通结实长绳，可系结、牵引或拆分。','carried','完好，盘起。'),entity('journal','手记','纸本与炭笔；可记载已获知事实。','carried','空白页充足。')];
export const stories={
 ...meijieStories,
 'library-delve':{
  id:'library-delve',title:'深入图书馆',original:'The Library Delve',author:'Willem-Jan / 1pagedungeons.com',source:'https://1pagedungeons.itch.io/leyebrary-opd',license:'https://creativecommons.org/licenses/by-sa/4.0/',
  tagline:'有些门，要用你记得的东西来打开。',summary:'五位管理员失踪，古老图书馆紧闭。会飞的书、无声的猫头鹰与不肯离去的守书人，等待你回答：知识值得怎样的代价？',tags:['奇幻探索','记忆代价','交谈与选择'],start:'entry',
  opening:"你是一名受托调查失踪事件的独行探险者。几天前，这座收藏秘术书籍的图书馆突然闭门，五位管理员再没有传出消息。委托交到你手里的，是一个尚无人能回答的问题：馆内究竟发生了什么，失联的人是否还活着？你带来照明和工具，打算先查明情况，再决定能做些什么。\n\n如今，你已经跨过入口，站在大厅的散乱书架之间。提灯照出翻倒的书册，也照出五具一动不动的尸体。它们上方各徘徊着一道苍白人影，低声交谈的声音混着纸页摩擦声，在高处回荡。听见你的脚步，幽影们转向这边，警惕地打量你。它们没有扑过来，却也没有主动回答你心里的疑问。\n\n大厅左右各有一道关着的门，门框上刻着同一句铭文：“献上一段重要的记忆，方可通行。”你还不知道这里为何索取记忆，也不清楚交出去后能否取回。门后发生什么，只凭大厅里的景象还无法断定；解释这一切的线索，或许就藏在眼前的痕迹和这些幽影的话里。\n\n你的提灯仍亮着，绳索、手记和一套细小的撬锁工具都随身带着。身后的入口是来路，你随时可以回到这里离开。此刻不必急着答应铭文上的交易：可以先向幽影表明来意，询问管理员遭遇了什么；也可以举灯检查尸体周围的痕迹，或靠近一道门看清锁具与刻字。你要先弄明白哪件事，由你决定。",
  places:{entry:room('入口大厅','五具管理员尸体与五道幽影留在遭洗劫的书架间；门框刻着以重要记忆换取通行的铭文。',['conjuration','necromancy']),conjuration:room('咒唤书区','书籍悬浮，边墙燃着魔法火；门边有可以站立的石地。',['entry','divination']),necromancy:room('死灵书区','泥土覆盖书区，书埋在地下六英尺。',['entry','transmutation']),divination:room('占卜书区','中央玻璃球中悬着一只幽灵眼睛；四周排满书架。',['conjuration']),transmutation:room('变化书区','书籍由不同的基本材料制成，许多沉重得难以搬动。',['necromancy'])},
  gates:[{a:'entry',b:'conjuration',flag:'open_conjuration'},{a:'entry',b:'necromancy',flag:'open_necromancy'},{a:'conjuration',b:'divination',flag:'open_divination'},{a:'necromancy',b:'transmutation',flag:'open_transmutation'}],
  entities:[...common,entity('picks','撬锁工具','细钩与张力扳手；可尝试困难的开锁，非万能钥匙。','carried','完好。'),npc('spirits','五位守书幽灵','entry','徘徊于尸体上方，低声说话，警惕来者。','生前的管理员，数日前被盗贼杀害，死后受束缚守护图书馆。知晓记忆门及盗书事件。使用或偷书会恶化态度，归还被盗书或惩罚凶手会改善；不会轻易提供无限帮助。'),entity('memory_archive','记忆档案','献出的角色记忆归档在此。只有玩家明确自愿指定的重要角色记忆才能被收走；无需提供现实隐私。','entry','尚未收取玩家的任何记忆。',false),npc('owls','智慧猫头鹰','conjuration','安静地栖在高处。','有智慧与自由意志，害怕幽灵；不是自动听命的宠物。'),npc('sarah','盗贼 Sarah','conjuration','藏在门边书架背后，持有一本被盗书。','与同伙杀死管理员；不能解锁门，每人持一本偷书，愿为新偷书付100金，有胜算时伏击，面对劣势或交易可谈判。'),npc('jay','盗贼 Jay','conjuration','与 Sarah 躲在一起。','盗贼同伙，逐利、自保；不能开门。'),npc('matthias','盗贼 Matthias','necromancy','在泥土地边看守赃物。','盗贼同伙，逐利、自保；不能开门。'),npc('quill','盗贼 Quill','divination','躲避中央眼睛的视线。','盗贼同伙，逐利、自保；不能开门。'),npc('needle','盗贼 Needle','transmutation','靠着沉重书架歇脚。','盗贼同伙，逐利、自保；不能开门。'),...['sarah','jay','matthias','quill','needle'].map((n,i)=>entity('stolen_'+n,'被盗书·'+n,'属于图书馆，内容以死语言写就；不能无代价使用。',['conjuration','conjuration','necromancy','divination','transmutation'][i],'由对应盗贼持有，必须通过真实交涉或行动才能取得。')),entity('eye','幽灵之眼','中央玻璃球，守书幽灵能借它观察此区。','divination','静静注视房间。',false),...['conjuration','necromancy','divination','transmutation'].map(n=>entity('books_'+n,'馆藏·'+n,'死语言注明效果，书籍属于图书馆；使用立即生效并影响幽灵态度。',''+n,'仍在本区；死灵书埋在地下六英尺，变化书材质各异。',false))],
  milestones:{...Object.fromEntries(['conjuration','necromancy','divination','transmutation'].map(n=>['open_'+n,{places:n==='divination'?['conjuration']:n==='transmutation'?['necromancy']:['entry'],refsAny:['picks','memory_archive'],rule:'解开对应门锁：实际困难撬锁成功，或玩家明确献出一段重要角色记忆。献记忆须同步更新memory_archive并填写memory_offer。只解开这一扇门。'}])),investigated:{places:['entry','conjuration','necromancy','divination','transmutation'],refsAny:['spirits','sarah','jay','matthias','quill','needle'],rule:'经过调查或交谈，确认管理员被盗贼所杀，幽灵因守书职责滞留；不能从后台直接得知。'}},
  endings:{leave:{title:'带着答案离开',text:'你离开图书馆。已经献出的记忆仍留在档案中；书籍与守书人的命运，取决于你实际做过的事。',places:['entry']}},
  laws:['全部四扇区间门初始上锁；未取得对应open标记不能通行。撬锁困难但并非绝对禁止，失败应给可用线索而非无穷重复。盗贼被困各区，没有解锁能力。','开局未授权献记忆。绝不代选或捏造玩家的珍贵经历；玩家可虚构角色记忆。先说明不可随意取回，再由玩家明确同意。每段记忆只开一扇门。','书籍效果选用原作范围：学派魔法、放逐一个幽灵、世界传闻、工具熟练、藏宝信息，或变化书变银、咒唤书召三只友好猫头鹰、死灵书会见亡者、占卜书窥视某地一分钟。不得变出本图之外可探索的新地图；本版不结算外部藏宝支线。','书籍尖叫、幽灵敌意、附身威胁等仅在偷用书或挑衅等因果触发后发展。不要每轮随机惩罚。不能凭取一书宣称所有幽灵获救；可选择离开，不强制献出记忆。'],
  changes:'中文单人化；固定盗贼所在区域，简化平面通道为四扇分区门；随机遭遇改为因果事件；战斗改为叙事冲突，不复刻职业数值；以调查与离开收束，不扩展区域外藏宝地图。记忆必须由玩家自愿指定。'
 },
 'ghosts-of-aramoor':{
  id:'ghosts-of-aramoor',title:'阿拉穆尔的亡魂',original:'The Ghosts of Aramoor',author:'Jason Renslow',source:'https://junkyardtornado.itch.io/the-ghosts-of-aramoor',license:'https://creativecommons.org/licenses/by-sa/4.0/',
  tagline:'海盗已经死了，小镇却仍在被劫掠。',summary:'地震之后，旧海盗的鬼魂开始偷走镇上的金银。沿着海岸新出现的裂口进入洞窟，寻找让亡魂停止归来的办法。',tags:['海岸怪谈','环境解谜','调查冒险'],start:'town',
  opening:"你以独行调查者的身份来到海滨小镇阿拉穆尔。镇长请你查一桩古怪的劫案：自从那场地震后，穿着旧式海盗服的鬼魂就开始在夜里进镇搜走金银。居民找不到能锁住它们的门，有人已经准备搬走。眼下你的任务是找到骚扰的来源，设法让镇民重新过上安稳日子；若能寻回失物，自然更好。\n\n听镇长讲述时，你看见一只被撬空的首饰盒。他把盒子合上，手指仍压在裂开的锁扣上。“旧海盗的传闻，这里一直都有。可真丢了东西，是地震之后的事。”他说。街边有人清点空掉的钱匣，有人低声争论今晚该住在哪里。你听到的目前都只是他们的见闻，鬼魂为何回来，还没有可靠的答案。\n\n现在，你与镇长站在镇口。往海边去的路就在前方，风带着潮水和湿石的气味吹来。“海岸新裂开了一个洞口，那些东西是从那一带来的。”镇长指向海滩，却说不清洞里有多深，更不知道怎样驱逐亡魂。他仍愿意回答你关于地震、失物和夜袭的询问。\n\n提灯、绳索、手记和撬杆都已备好，你没有同行的护卫，也不必立刻闯进未知的洞穴。可以先问清鬼魂出现的时间、偷走了什么，确认哪些说法来自亲眼目击；也可以沿路去海滩，留意失物与新洞口的痕迹，到了那里再决定如何深入。镇长会留在镇上等消息，来路也为你留着。",
  places:{town:room('阿拉穆尔镇','居民正在清点失物，镇长留在镇口等消息。',['beach']),beach:room('洞外海滩','地震露出的洞口通向地下，潮线上散着几件镇民失物。',['town','passage','sea']),passage:room('湿滑斜道','石道向洞内倾斜，下去容易，攀回海滩需要留心支点。',['beach','camp']),camp:room('洞内沙滩','废弃营地与一艘搁浅海盗船挤在岩洞中；跳板通向甲板，海水通向洞外。',['passage','deck','sea']),deck:room('海盗船甲板','旧船的甲板开着一扇通往货舱的活板门，四周连着洞内沙滩与海水。',['camp','hold','sea']),hold:room('船下货舱','拥挤的旧货舱没有独立出口，必须沿梯子返回甲板。',['deck']),sea:room('洞内海水与出海口','狭长水道通向外海；水下阴影难以辨清。',['camp','deck','beach'])},
  gates:[],entities:[...common,entity('crowbar','撬杆','普通金属杠杆，可撬动木箱、帮助搬运，不能徒手抬船。','carried','完好。'),npc('mayor','镇长','town','担忧居民离开，希望找到失物与骚扰根源。','知道地震、洞口、旧海盗传闻、失窃金银和出现时序，不知道船沉重搁浅的内幕。'),entity('lost_trinkets','海滩失物','镇民可辨认的小件金银物饰。','beach','散落在潮线，沾沙。'),entity('camp_gear','旧营具','旧绳、锈灯与锅；可以实际拆分取用，锈灯没有可用燃油。','camp','陈旧，留在沙上。'),npc('skeletons','海盗骷髅','camp','半埋沙中，受惊扰可苏醒。','骷髅会复起；击碎后的骨头会汇入船长，使其更强，杀死骷髅不解除骚扰。'),entity('chest','半埋的旧箱','藏有好朗姆、镶宝石弯刀与海盗帽，挖出打开才看见内容；可用creates分出实体，箱子因此damaged。','camp','半埋洞壁下方，箱盖闭合。'),npc('captain','亡魂船长','deck','幽灵在骨堆上方盘旋，骨头渐渐拼成怪物。','守着船甲板，绝不会离开甲板；击碎骷髅会使其变强，箱中的宝石弯刀能更有效伤害它。骷髅和船长可重生，不是最终解法。'),entity('loot','失窃金银货物','大量镇民金银重压船体，使船搁浅。可逐批移出，不可一手收入背包；完全移出用place=camp/beach/town或consumed表示已弃海，须有搬运过程。','hold','沉重货堆压住船；全部留在货舱。',true),npc('snakes','货舱毒蛇','hold','藏在货堆间。','惊扰会防御攻击；可用工具驱离、隔开或绕行。'),entity('ship','搁浅的海盗船','旧船仍可漂浮，卸下货舱重物后能离开海洞。','deck','搁浅，未驶离。',false)],
  milestones:{unburdened:{places:['hold','deck','camp'],refsAny:['loot'],entityRules:[{id:'loot',notPlaces:['hold','deck','carried']}],rule:'货舱金银已通过实际搬运移到船外或弃海，确实减重；只说调查、抬几枚金币不算。'},sailed:{places:['deck','sea','camp'],requires:['unburdened'],refsAny:['ship'],rule:'实际让减重的船浮起并沿海水离开洞穴，不只是制定计划。更新ship事实说明船已经离洞。'},returned:{places:['town'],refsAny:['loot'],entityRules:[{id:'loot',place:'town'}],rule:'把移出的金银实际送还镇民；知道所在不等于归还。'}},
  endings:{resolved:{title:'离港的亡魂',text:'海盗船已离开洞穴，当地的夜袭源头随之远去。海盗没有被永久净化；外海可能还会听到它的传闻。',places:['town'],requires:['sailed']},leave:{title:'暂别海岸',text:'你带着实际获得的线索回到镇上，结束了这次调查。未解决的事情仍留在海岸。',places:['town']}},
  laws:['原作真相：货舱被偷来的金银压得过重，船搁浅。真正解除当地骚扰需卸重让船重新浮起并驶离，不是打倒船长或骷髅。','sailed之后不可再次从camp登上已远去的船。若玩家随船而行，叙述其从出海口安全上岸到sea/beach，不能隔空操纵船。','船长不能离开deck。骷髅被打散会复起并强化船长；不能以击杀结算永久超度。镇长不能告诉玩家尚未调查的真相。','可以通过观察吃水、货舱重物、旧绳等逐步推断，无需战斗。单人搬运需绳、杠杆或协商帮助，可用一段连续劳动完成，不按轮数扣生命；若途中出现新危险则停下。船外可以向邻近甲板投物，但不能隔墙取货。','金银体量太大，不得装入随身carried；已运到camp/beach后可沿走过的路线送往town，须逐地点移送。'],
  changes:'增加小镇交谈起点；保留原作六处海洞区域与卸重离港的核心解法；不使用战斗数值及固定倒计时，以单人可实施的工具、谈判和搬运处理冲突；明确离港不等于净化亡魂。'
 },
 'goodbye-shooting-star':{
  id:'goodbye-shooting-star',title:'再见，流星',original:'Goodbye Shooting Star',author:'Jason Renslow',source:'https://junkyardtornado.itch.io/goodbye-shooting-star',license:'https://creativecommons.org/licenses/by-sa/4.0/',
  tagline:'失联一年后，流星号又出现了。',summary:'一艘无人应答的科研船，一份价值不明的实验资料，还有另一支赶来回收它的队伍。进入冷暗的船舱，决定哪些东西值得带回。',tags:['科幻悬疑','派系交涉','探索撤离'],start:'airlock_a',
  opening:"你是一名独自接下委托的登舰调查者。失联一年的科研船“流星号”重新被发现，却始终不回应呼叫。委托资料说，它曾研究一种超级士兵血清，留下的实验记录与样品可能很有价值。你要做的是进入船内核实情况，尽可能带回有依据的发现；至于里面究竟出了什么事，资料没有给出答案。\n\n对接锁响了三下。你从自己的接驳艇跨进一号气闸，头灯的光沿舱壁扫过，最后落在两条去路上。脚下的重力还在，空气冰冷，仪表读数显示应急生命维持仍在工作。这里并未彻底断电，但也不像有人正常值守的飞船。你停下来听了听，门内没有人应答。\n\n眼前的标识分别指向货舱一和研究实验室。货舱通道处在头灯边缘，实验室那边也没有传来交谈声。船员的去向、实验的结果、样品能否安全接触，都需要你自己寻找证据；一份说它“值钱”的委托，并不能替你回答这些问题。\n\n你随身有头灯、通信终端、绳索和手记。头灯用来照明，终端可以联络和保存实际取得的资料，绳索可以帮助探路；它们不是修复整艘船的万能工具。接驳艇仍停在身后的气闸外，是明确的撤离途径。你可以先在门口观察两侧通道、试着呼叫船内人员，再选择去货舱查看环境，或前往实验室找可读的记录。先调查到什么程度、遇到什么情况就退回，都可以由你自己定。",
  places:{airlock_a:room('一号气闸','你的接驳艇仍对接在外，门内通向货舱一与实验室。',['cargo_a','lab']),cargo_a:room('货舱一','科研耗材箱沿货舱两侧排列，走廊通往引擎。',['airlock_a','cargo_b','engine']),cargo_b:room('货舱二','通用货物、工具与维修零件留在架上。',['cargo_a','airlock_b','engine']),airlock_b:room('二号气闸','另一端的对接口，通向货舱二与实验室。',['cargo_b','lab']),lab:room('研究实验室','试验台、资料终端和封存柜处在冷暗中；多个舱门通向别处。',['airlock_a','airlock_b','living','weapons','sensors']),living:room('居住舱','寂静的休息区连着舰桥，通风格栅散在墙上。',['lab','bridge']),bridge:room('舰桥','主控制台大部离线，透过舷窗只能看见星空。',['living']),engine:room('引擎室','主引擎待修，窄廊连接生命维持与机器人库。',['cargo_a','cargo_b','life_support','robots']),life_support:room('生命维持室','应急循环仍工作；正常温控、照明支持等系统待修。',['engine']),robots:room('机器人库','几台简易作业机器人停在充电槽中。',['engine']),weapons:room('武器控制室','武器系统离线，维修面板闭合。',['lab']),sensors:room('传感器室','传感器主阵列离线。',['lab'])},gates:[],
  entities:[entity('headlamp','头灯','电灯，没有可点燃物品的明火，不模拟固定电量倒计时。','carried','完好，亮着。'),common[1],common[2],entity('terminal','通信终端','可通信、保存已经取得的资料和维修手册，不具备万能黑客功能。','carried','工作正常，尚未下载舰内资料。'),entity('research','实验记录','科研日志，实际查阅可知狗接受血清后失控并杀死船员；从未证明人体安全，可下载到terminal。','lab','留在实验台终端，可访问的资料目录仍有供电。',false),entity('samples','血清样品','超级士兵实验制剂；危险，未证明人体安全。拿取需观察封存情况，不可凭闻气味判断无害。','lab','少量样品封存在容器里。'),entity('chemicals','科研耗材','杂乱试剂，乱配血清危险，不能凭空制造解药。','cargo_a','装在材料箱里。',false),entity('toolkit','维修工具与零件','普通船用维修工具、少量备用件和对应操作手册。可据手册实施有限维修，不代表主角突然具备所有专业知识。','cargo_b','一套可搬动的工具箱，完整。'),npc('dog','变异实验犬','living','在居住舱守着骨头和杂物，警觉。','血清试验后的狗，极顽强、凶猛，杀死并吞食船员；保护飞船尤其居住舱，熟悉通风管可很快移动。不是邪神或会说人话的怪物。可隔门观察、诱导、避开；不能被一击消灭或一句话驯服。'),entity('bones','船员遗骸与杂物','全体船员已死，遗骸被狗藏在居住舱。须实际进入或有视线探查才能看见。','living','堆在犬巢附近。',false),npc('hounds','钢铁猎犬佣兵队','airlock_b','尚在接近飞船，未登舰。','由 Cyrus Janno 率领，想修好整艘船并拖回出售。玩家探索后才从另一气闸登舰；不自动知道玩家所知。可就资料、样品和船权交易，不是无条件敌人。'),...['engine','life_support','weapons','sensors'].map(id=>entity(id+'_system',({engine:'主引擎',life_support:'常规生命维持',weapons:'武器系统',sensors:'传感器系统'})[id],'需在本室使用工具、零件和操作手册完成实际维修；基础应急生命维持始终独立运行。',id,'待修，尚未恢复正常功能。',false)),entity('robots_unit','简易作业机器人','能执行简单搬运和有限检修辅助，不能代替科学家，也不能完成未确认危险的复杂任务。','robots','停机待指令。',false),entity('console','舰桥控制台','只能控制已经修好的系统，不能通过按键隔空修复故障。','bridge','待机，可查询有限故障清单。',false)],
  milestones:{research_read:{places:['lab'],refsAny:['research'],rule:'实际查阅实验日志，揭示犬实验及全员死亡线索。'},data_saved:{places:['lab'],requires:['research_read'],refsAny:['research','terminal'],entityRules:[{id:'terminal',place:'carried'}],rule:'实际将科研资料复制到随身终端，同步更新terminal事实；只看过不等于已复制。'},hounds_arrived:{places:['airlock_b','cargo_b','lab','airlock_a','cargo_a','engine','living','bridge','life_support','robots','weapons','sensors'],rule:'玩家已开始探索后以对接震动或无线电宣告钢铁猎犬到来；他们从二号气闸登舰，不瞬移至玩家身边。'},...Object.fromEntries(['engine','life_support','weapons','sensors'].map(id=>['fixed_'+id,{places:[id],refsAny:[id+'_system','toolkit'],entityRules:[{id:'toolkit',place:'carried',intact:true}],rule:'在对应系统现场按照手册进行实际维修，需要工具与材料，同步更新系统实体；遥控台点击不算维修。'}])),deal:{places:['airlock_b','lab','bridge','cargo_b'],requires:['hounds_arrived','fixed_engine'],refsAny:['hounds'],rule:'实际与佣兵谈妥船只回收及玩家离开的条件，玩家明确同意；意向或单方口头宣称不算协议。'}},
  endings:{evidence:{title:'带回来的证据',text:'你乘接驳艇离开流星号，保存了实际复制的研究记录。血清没有因此被证明安全；关于它的下一步仍需谨慎决定。',places:['airlock_a'],requires:['data_saved'],entityRules:[{id:'terminal',place:'carried',intact:true}]},salvage:{title:'一艘船的价码',text:'你按已谈妥的回收协议离开，流星号交给了钢铁猎犬。协议和带走的物品以这次真实交涉为准。',places:['airlock_a'],requires:['deal']},leave:{title:'回航信号',text:'你返回接驳艇，结束登舰。带走的是实际取得的物品与发现；没有查明的舱室仍然沉默。',places:['airlock_a']}},
  laws:['完整船员均已死，不能新增幸存者。真相需查阅记录或观察犬与遗骸后发现；玩家开局仅知研究目的。','玩家行动开始推动探索后可让佣兵到来；澄清、询问与思考不触发惩罚倒计时。hounds_arrived之前佣兵尚未登舰，不能近距离交谈或转移物件。','犬可经通风管移动，但人爬管很困难，玩家正常移动必须遵循房间连接。狗的秘密和远处位置不可当作玩家实时知识。','修复分别在各室完成，需toolkit、手册与真实操作；有专业门槛时可请机器人辅助或谈判佣兵帮助。bridge只能控制已修复系统，fixed_engine不等于全舰恢复。','基础应急空气循环和重力始终有效，不制造问几轮就缺氧的期限。主要光照和温控失修导致冷暗。','血清没有安全的人体结论；不能凭一次试验或模型叙述创造解药。NPC不能突然知道玩家秘密。'],
  changes:'中文单人改编，保留原船舱网络、实验犬真相与钢铁猎犬回收整船的动机；对接艇作为一号气闸离场方式；战斗改为规避、工具和协商；新增明确撤离与交易结局；应急生命维持不设统一倒计时。不复用原稿图片。'
 }
};
